package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admissionnotes generated by hbm2java
 */
@Entity
@Table(name="admissionnotes"
    ,catalog="extended"
)
public class Admissionnotes  implements java.io.Serializable {


     private Integer noteid;
     private int visitid;
     private String doctorsid;
     private String note;
     private Date date;

    public Admissionnotes() {
    }

	
    public Admissionnotes(int visitid, String note, Date date) {
        this.visitid = visitid;
        this.note = note;
        this.date = date;
    }
    public Admissionnotes(int visitid, String doctorsid, String note, Date date) {
       this.visitid = visitid;
       this.doctorsid = doctorsid;
       this.note = note;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="noteid", unique=true, nullable=false)
    public Integer getNoteid() {
        return this.noteid;
    }
    
    public void setNoteid(Integer noteid) {
        this.noteid = noteid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="doctorsid")
    public String getDoctorsid() {
        return this.doctorsid;
    }
    
    public void setDoctorsid(String doctorsid) {
        this.doctorsid = doctorsid;
    }
    
    @Column(name="note", nullable=false, length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


