package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Allergies generated by hbm2java
 */
@Entity
@Table(name="allergies"
    ,catalog="extended"
)
public class Allergies  implements java.io.Serializable {


     private Integer allergyid;
     private String type;
     private String name;
     private String possibleRxns;
     private String suggestedTreatment;

    public Allergies() {
    }

    public Allergies(String type, String name, String possibleRxns, String suggestedTreatment) {
       this.type = type;
       this.name = name;
       this.possibleRxns = possibleRxns;
       this.suggestedTreatment = suggestedTreatment;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="allergyid", unique=true, nullable=false)
    public Integer getAllergyid() {
        return this.allergyid;
    }
    
    public void setAllergyid(Integer allergyid) {
        this.allergyid = allergyid;
    }
    
    @Column(name="type", length=65535)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="possible_rxns", length=65535)
    public String getPossibleRxns() {
        return this.possibleRxns;
    }
    
    public void setPossibleRxns(String possibleRxns) {
        this.possibleRxns = possibleRxns;
    }
    
    @Column(name="suggested_treatment", length=65535)
    public String getSuggestedTreatment() {
        return this.suggestedTreatment;
    }
    
    public void setSuggestedTreatment(String suggestedTreatment) {
        this.suggestedTreatment = suggestedTreatment;
    }




}


