package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppointmentType generated by hbm2java
 */
@Entity
@Table(name="appointment_type"
    ,catalog="extended"
)
public class AppointmentType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String staffId;
     private Date dateAdded;

    public AppointmentType() {
    }

    public AppointmentType(String name, String description, String staffId, Date dateAdded) {
       this.name = name;
       this.description = description;
       this.staffId = staffId;
       this.dateAdded = dateAdded;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="staff_id", nullable=false, length=50)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_added", nullable=false, length=10)
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }




}


