package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArchivedRefRangeDet generated by hbm2java
 */
@Entity
@Table(name="archived_ref_range_det"
    ,catalog="extended"
)
public class ArchivedRefRangeDet  implements java.io.Serializable {


     private int id;
     private int detailedinvRefrangeTypeId;
     private String detFrom;
     private String detTo;
     private String MLower;
     private String MUpper;
     private String FLower;
     private String FUpper;
     private String oerderid;
     private int patienttreatmentid;

    public ArchivedRefRangeDet() {
    }

    public ArchivedRefRangeDet(int id, int detailedinvRefrangeTypeId, String detFrom, String detTo, String MLower, String MUpper, String FLower, String FUpper, String oerderid, int patienttreatmentid) {
       this.id = id;
       this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
       this.detFrom = detFrom;
       this.detTo = detTo;
       this.MLower = MLower;
       this.MUpper = MUpper;
       this.FLower = FLower;
       this.FUpper = FUpper;
       this.oerderid = oerderid;
       this.patienttreatmentid = patienttreatmentid;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="detailedinv_refrange_type_id", nullable=false)
    public int getDetailedinvRefrangeTypeId() {
        return this.detailedinvRefrangeTypeId;
    }
    
    public void setDetailedinvRefrangeTypeId(int detailedinvRefrangeTypeId) {
        this.detailedinvRefrangeTypeId = detailedinvRefrangeTypeId;
    }
    
    @Column(name="det_from", nullable=false, length=11)
    public String getDetFrom() {
        return this.detFrom;
    }
    
    public void setDetFrom(String detFrom) {
        this.detFrom = detFrom;
    }
    
    @Column(name="det_to", nullable=false, length=11)
    public String getDetTo() {
        return this.detTo;
    }
    
    public void setDetTo(String detTo) {
        this.detTo = detTo;
    }
    
    @Column(name="m_lower", nullable=false, length=11)
    public String getMLower() {
        return this.MLower;
    }
    
    public void setMLower(String MLower) {
        this.MLower = MLower;
    }
    
    @Column(name="m_upper", nullable=false, length=11)
    public String getMUpper() {
        return this.MUpper;
    }
    
    public void setMUpper(String MUpper) {
        this.MUpper = MUpper;
    }
    
    @Column(name="f_lower", nullable=false, length=11)
    public String getFLower() {
        return this.FLower;
    }
    
    public void setFLower(String FLower) {
        this.FLower = FLower;
    }
    
    @Column(name="f_upper", nullable=false, length=11)
    public String getFUpper() {
        return this.FUpper;
    }
    
    public void setFUpper(String FUpper) {
        this.FUpper = FUpper;
    }
    
    @Column(name="oerderid", nullable=false, length=65535)
    public String getOerderid() {
        return this.oerderid;
    }
    
    public void setOerderid(String oerderid) {
        this.oerderid = oerderid;
    }
    
    @Column(name="patienttreatmentid", nullable=false)
    public int getPatienttreatmentid() {
        return this.patienttreatmentid;
    }
    
    public void setPatienttreatmentid(int patienttreatmentid) {
        this.patienttreatmentid = patienttreatmentid;
    }




}


