package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BackupSyncTable generated by hbm2java
 */
@Entity
@Table(name="backup_sync_table"
    ,catalog="extended"
)
public class BackupSyncTable  implements java.io.Serializable {


     private Integer id;
     private Integer syncfrequency;
     private Date dayDate;
     private Integer time;
     private String amPm;
     private Integer backFrequncy;

    public BackupSyncTable() {
    }

    public BackupSyncTable(Integer syncfrequency, Date dayDate, Integer time, String amPm, Integer backFrequncy) {
       this.syncfrequency = syncfrequency;
       this.dayDate = dayDate;
       this.time = time;
       this.amPm = amPm;
       this.backFrequncy = backFrequncy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="syncfrequency")
    public Integer getSyncfrequency() {
        return this.syncfrequency;
    }
    
    public void setSyncfrequency(Integer syncfrequency) {
        this.syncfrequency = syncfrequency;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="day_date", length=10)
    public Date getDayDate() {
        return this.dayDate;
    }
    
    public void setDayDate(Date dayDate) {
        this.dayDate = dayDate;
    }
    
    @Column(name="time")
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }
    
    @Column(name="am_pm", length=10)
    public String getAmPm() {
        return this.amPm;
    }
    
    public void setAmPm(String amPm) {
        this.amPm = amPm;
    }
    
    @Column(name="back_frequncy")
    public Integer getBackFrequncy() {
        return this.backFrequncy;
    }
    
    public void setBackFrequncy(Integer backFrequncy) {
        this.backFrequncy = backFrequncy;
    }




}


