package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bed generated by hbm2java
 */
@Entity
@Table(name="bed"
    ,catalog="extended"
)
public class Bed  implements java.io.Serializable {


     private Integer bedid;
     private String description;
     private boolean occuppied;
     private String wardOrRoom;
     private int wardid;
     private int roomid;

    public Bed() {
    }

    public Bed(String description, boolean occuppied, String wardOrRoom, int wardid, int roomid) {
       this.description = description;
       this.occuppied = occuppied;
       this.wardOrRoom = wardOrRoom;
       this.wardid = wardid;
       this.roomid = roomid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="bedid", unique=true, nullable=false)
    public Integer getBedid() {
        return this.bedid;
    }
    
    public void setBedid(Integer bedid) {
        this.bedid = bedid;
    }
    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="occuppied", nullable=false)
    public boolean isOccuppied() {
        return this.occuppied;
    }
    
    public void setOccuppied(boolean occuppied) {
        this.occuppied = occuppied;
    }
    
    @Column(name="ward_or_room", nullable=false, length=65535)
    public String getWardOrRoom() {
        return this.wardOrRoom;
    }
    
    public void setWardOrRoom(String wardOrRoom) {
        this.wardOrRoom = wardOrRoom;
    }
    
    @Column(name="wardid", nullable=false)
    public int getWardid() {
        return this.wardid;
    }
    
    public void setWardid(int wardid) {
        this.wardid = wardid;
    }
    
    @Column(name="roomid", nullable=false)
    public int getRoomid() {
        return this.roomid;
    }
    
    public void setRoomid(int roomid) {
        this.roomid = roomid;
    }




}


