package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BodyPartOptions generated by hbm2java
 */
@Entity
@Table(name="body_part_options"
    ,catalog="extended"
)
public class BodyPartOptions  implements java.io.Serializable {


     private Integer bodyPartId;
     private String bodyPart;

    public BodyPartOptions() {
    }

    public BodyPartOptions(String bodyPart) {
       this.bodyPart = bodyPart;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="body_part_id", unique=true, nullable=false)
    public Integer getBodyPartId() {
        return this.bodyPartId;
    }
    
    public void setBodyPartId(Integer bodyPartId) {
        this.bodyPartId = bodyPartId;
    }
    
    @Column(name="body_part", nullable=false)
    public String getBodyPart() {
        return this.bodyPart;
    }
    
    public void setBodyPart(String bodyPart) {
        this.bodyPart = bodyPart;
    }




}


