package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CardPrinting generated by hbm2java
 */
@Entity
@Table(name="card_printing"
    ,catalog="extended"
)
public class CardPrinting  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private double price;
     private int printCount;
     private Date lastPrintDate;
     private String orderedby;

    public CardPrinting() {
    }

    public CardPrinting(String patientid, double price, int printCount, Date lastPrintDate, String orderedby) {
       this.patientid = patientid;
       this.price = price;
       this.printCount = printCount;
       this.lastPrintDate = lastPrintDate;
       this.orderedby = orderedby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="patientid", nullable=false)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    
    @Column(name="print_count", nullable=false)
    public int getPrintCount() {
        return this.printCount;
    }
    
    public void setPrintCount(int printCount) {
        this.printCount = printCount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_print_date", nullable=false, length=19)
    public Date getLastPrintDate() {
        return this.lastPrintDate;
    }
    
    public void setLastPrintDate(Date lastPrintDate) {
        this.lastPrintDate = lastPrintDate;
    }
    
    @Column(name="orderedby", nullable=false)
    public String getOrderedby() {
        return this.orderedby;
    }
    
    public void setOrderedby(String orderedby) {
        this.orderedby = orderedby;
    }




}


