package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CharacteristicOptions generated by hbm2java
 */
@Entity
@Table(name="characteristic_options"
    ,catalog="extended"
)
public class CharacteristicOptions  implements java.io.Serializable {


     private Integer characteristicId;
     private String characteristic;

    public CharacteristicOptions() {
    }

    public CharacteristicOptions(String characteristic) {
       this.characteristic = characteristic;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="characteristic_id", unique=true, nullable=false)
    public Integer getCharacteristicId() {
        return this.characteristicId;
    }
    
    public void setCharacteristicId(Integer characteristicId) {
        this.characteristicId = characteristicId;
    }
    
    @Column(name="characteristic", nullable=false)
    public String getCharacteristic() {
        return this.characteristic;
    }
    
    public void setCharacteristic(String characteristic) {
        this.characteristic = characteristic;
    }




}


