package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clerkingquestion generated by hbm2java
 */
@Entity
@Table(name="clerkingquestion"
    ,catalog="extended"
)
public class Clerkingquestion  implements java.io.Serializable {


     private Integer clerkid;
     private String question;
     private int frequecy;
     private int categoryId;

    public Clerkingquestion() {
    }

    public Clerkingquestion(String question, int frequecy, int categoryId) {
       this.question = question;
       this.frequecy = frequecy;
       this.categoryId = categoryId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="clerkid", unique=true, nullable=false)
    public Integer getClerkid() {
        return this.clerkid;
    }
    
    public void setClerkid(Integer clerkid) {
        this.clerkid = clerkid;
    }
    
    @Column(name="question", nullable=false, length=250)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    
    @Column(name="frequecy", nullable=false)
    public int getFrequecy() {
        return this.frequecy;
    }
    
    public void setFrequecy(int frequecy) {
        this.frequecy = frequecy;
    }
    
    @Column(name="category_id", nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }




}


