package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClientInfo generated by hbm2java
 */
@Entity
@Table(name="client_info"
    ,catalog="extended"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class ClientInfo  implements java.io.Serializable {


     private String uniqueId;
     private String lastName;
     private String otherNames;
     private Date dateOfBirth;
     private String gender;
     private String email;
     private String telephone;
     private String nextOfKin;
     private String nextOfKinContact;
     private String address;
     private String country;
     private String city;
     private String employer;
     private Date dateOfRegistration;
     private String maritalStatus;
     private Integer lastClaimId;
     private Integer lastVisitId;
     private String folderNumber;
     private Set<Pharmacyorder> pharmacyorders = new HashSet<Pharmacyorder>(0);

    public ClientInfo() {
    }

	
    public ClientInfo(String uniqueId, String lastName, String otherNames, Date dateOfBirth, String gender, String telephone, String nextOfKin, String nextOfKinContact, String address, String country, String city, String employer, Date dateOfRegistration, String maritalStatus) {
        this.uniqueId = uniqueId;
        this.lastName = lastName;
        this.otherNames = otherNames;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.telephone = telephone;
        this.nextOfKin = nextOfKin;
        this.nextOfKinContact = nextOfKinContact;
        this.address = address;
        this.country = country;
        this.city = city;
        this.employer = employer;
        this.dateOfRegistration = dateOfRegistration;
        this.maritalStatus = maritalStatus;
    }
    public ClientInfo(String uniqueId, String lastName, String otherNames, Date dateOfBirth, String gender, String email, String telephone, String nextOfKin, String nextOfKinContact, String address, String country, String city, String employer, Date dateOfRegistration, String maritalStatus, Integer lastClaimId, Integer lastVisitId, String folderNumber, Set<Pharmacyorder> pharmacyorders) {
       this.uniqueId = uniqueId;
       this.lastName = lastName;
       this.otherNames = otherNames;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.email = email;
       this.telephone = telephone;
       this.nextOfKin = nextOfKin;
       this.nextOfKinContact = nextOfKinContact;
       this.address = address;
       this.country = country;
       this.city = city;
       this.employer = employer;
       this.dateOfRegistration = dateOfRegistration;
       this.maritalStatus = maritalStatus;
       this.lastClaimId = lastClaimId;
       this.lastVisitId = lastVisitId;
       this.folderNumber = folderNumber;
       this.pharmacyorders = pharmacyorders;
    }
   
     @Id 
    
    @Column(name="unique_id", unique=true, nullable=false, length=50)
    public String getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }
    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="other_names", nullable=false, length=100)
    public String getOtherNames() {
        return this.otherNames;
    }
    
    public void setOtherNames(String otherNames) {
        this.otherNames = otherNames;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", nullable=false, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    
    @Column(name="gender", nullable=false, length=100)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="email", unique=true, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="telephone", nullable=false, length=100)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    @Column(name="next_of_kin", nullable=false, length=65535)
    public String getNextOfKin() {
        return this.nextOfKin;
    }
    
    public void setNextOfKin(String nextOfKin) {
        this.nextOfKin = nextOfKin;
    }
    
    @Column(name="next_of_kin_contact", nullable=false, length=100)
    public String getNextOfKinContact() {
        return this.nextOfKinContact;
    }
    
    public void setNextOfKinContact(String nextOfKinContact) {
        this.nextOfKinContact = nextOfKinContact;
    }
    
    @Column(name="address", nullable=false, length=65535)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="country", nullable=false, length=65535)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="city", nullable=false, length=65535)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="employer", nullable=false, length=65535)
    public String getEmployer() {
        return this.employer;
    }
    
    public void setEmployer(String employer) {
        this.employer = employer;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_of_registration", nullable=false, length=10)
    public Date getDateOfRegistration() {
        return this.dateOfRegistration;
    }
    
    public void setDateOfRegistration(Date dateOfRegistration) {
        this.dateOfRegistration = dateOfRegistration;
    }
    
    @Column(name="marital_status", nullable=false, length=20)
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    
    @Column(name="last_claim_id")
    public Integer getLastClaimId() {
        return this.lastClaimId;
    }
    
    public void setLastClaimId(Integer lastClaimId) {
        this.lastClaimId = lastClaimId;
    }
    
    @Column(name="last_visit_id")
    public Integer getLastVisitId() {
        return this.lastVisitId;
    }
    
    public void setLastVisitId(Integer lastVisitId) {
        this.lastVisitId = lastVisitId;
    }
    
    @Column(name="folder_number", length=100)
    public String getFolderNumber() {
        return this.folderNumber;
    }
    
    public void setFolderNumber(String folderNumber) {
        this.folderNumber = folderNumber;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="clientInfo")
    public Set<Pharmacyorder> getPharmacyorders() {
        return this.pharmacyorders;
    }
    
    public void setPharmacyorders(Set<Pharmacyorder> pharmacyorders) {
        this.pharmacyorders = pharmacyorders;
    }




}


