package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClinicInventoryRequests generated by hbm2java
 */
@Entity
@Table(name="clinic_inventory_requests"
    ,catalog="extended"
)
public class ClinicInventoryRequests  implements java.io.Serializable {


     private Integer requisitionid;
     private String itemcode;
     private String orderer;
     private Date orderdate;
     private Date deliverydate;
     private String deliverer;
     private String status;
     private String unit;
     private int requestedquantity;
     private int deliveredquantity;

    public ClinicInventoryRequests() {
    }

	
    public ClinicInventoryRequests(String itemcode, String orderer, Date orderdate, String status, String unit, int requestedquantity, int deliveredquantity) {
        this.itemcode = itemcode;
        this.orderer = orderer;
        this.orderdate = orderdate;
        this.status = status;
        this.unit = unit;
        this.requestedquantity = requestedquantity;
        this.deliveredquantity = deliveredquantity;
    }
    public ClinicInventoryRequests(String itemcode, String orderer, Date orderdate, Date deliverydate, String deliverer, String status, String unit, int requestedquantity, int deliveredquantity) {
       this.itemcode = itemcode;
       this.orderer = orderer;
       this.orderdate = orderdate;
       this.deliverydate = deliverydate;
       this.deliverer = deliverer;
       this.status = status;
       this.unit = unit;
       this.requestedquantity = requestedquantity;
       this.deliveredquantity = deliveredquantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="requisitionid", unique=true, nullable=false)
    public Integer getRequisitionid() {
        return this.requisitionid;
    }
    
    public void setRequisitionid(Integer requisitionid) {
        this.requisitionid = requisitionid;
    }
    
    @Column(name="itemcode", nullable=false, length=100)
    public String getItemcode() {
        return this.itemcode;
    }
    
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }
    
    @Column(name="orderer", nullable=false, length=65535)
    public String getOrderer() {
        return this.orderer;
    }
    
    public void setOrderer(String orderer) {
        this.orderer = orderer;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orderdate", nullable=false, length=19)
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deliverydate", length=19)
    public Date getDeliverydate() {
        return this.deliverydate;
    }
    
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }
    
    @Column(name="deliverer", length=65535)
    public String getDeliverer() {
        return this.deliverer;
    }
    
    public void setDeliverer(String deliverer) {
        this.deliverer = deliverer;
    }
    
    @Column(name="status", nullable=false, length=65535)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="unit", nullable=false, length=65535)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    
    @Column(name="requestedquantity", nullable=false)
    public int getRequestedquantity() {
        return this.requestedquantity;
    }
    
    public void setRequestedquantity(int requestedquantity) {
        this.requestedquantity = requestedquantity;
    }
    
    @Column(name="deliveredquantity", nullable=false)
    public int getDeliveredquantity() {
        return this.deliveredquantity;
    }
    
    public void setDeliveredquantity(int deliveredquantity) {
        this.deliveredquantity = deliveredquantity;
    }




}


