package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,catalog="extended"
)
public class Department  implements java.io.Serializable {


     private Integer departmentid;
     private String department;

    public Department() {
    }

    public Department(String department) {
       this.department = department;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="departmentid", unique=true, nullable=false)
    public Integer getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
    
    @Column(name="department", nullable=false, length=65535)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


