package entities;
// Generated Oct 11, 2012 6:51:47 AM by Hibernate Tools 3.2.1.GA



/**
 * DetailedinvRefrangeType generated by hbm2java
 */
public class DetailedinvRefrangeType  implements java.io.Serializable {


     private Integer id;
     private int detailedinvId;
     private String refRangeType;

    public DetailedinvRefrangeType() {
    }

    public DetailedinvRefrangeType(int detailedinvId, String refRangeType) {
       this.detailedinvId = detailedinvId;
       this.refRangeType = refRangeType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDetailedinvId() {
        return this.detailedinvId;
    }
    
    public void setDetailedinvId(int detailedinvId) {
        this.detailedinvId = detailedinvId;
    }
    public String getRefRangeType() {
        return this.refRangeType;
    }
    
    public void setRefRangeType(String refRangeType) {
        this.refRangeType = refRangeType;
    }




}


