package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetailedinvPosinvresults generated by hbm2java
 */
@Entity
@Table(name="detailedinv_posinvresults"
    ,catalog="extended"
)
public class DetailedinvPosinvresults  implements java.io.Serializable {


     private Integer detailedinvPosinvresultId;
     private int detailedinvId;
     private int posinvresultId;

    public DetailedinvPosinvresults() {
    }

    public DetailedinvPosinvresults(int detailedinvId, int posinvresultId) {
       this.detailedinvId = detailedinvId;
       this.posinvresultId = posinvresultId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="detailedinv_posinvresult_id", unique=true, nullable=false)
    public Integer getDetailedinvPosinvresultId() {
        return this.detailedinvPosinvresultId;
    }
    
    public void setDetailedinvPosinvresultId(Integer detailedinvPosinvresultId) {
        this.detailedinvPosinvresultId = detailedinvPosinvresultId;
    }
    
    @Column(name="detailedinv_id", nullable=false)
    public int getDetailedinvId() {
        return this.detailedinvId;
    }
    
    public void setDetailedinvId(int detailedinvId) {
        this.detailedinvId = detailedinvId;
    }
    
    @Column(name="posinvresult_id", nullable=false)
    public int getPosinvresultId() {
        return this.posinvresultId;
    }
    
    public void setPosinvresultId(int posinvresultId) {
        this.posinvresultId = posinvresultId;
    }




}


