package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DiagnosticGroupings generated by hbm2java
 */
@Entity
@Table(name="diagnostic_groupings"
    ,catalog="extended"
)
public class DiagnosticGroupings  implements java.io.Serializable {


     private String code;
     private String descriptio;

    public DiagnosticGroupings() {
    }

    public DiagnosticGroupings(String code, String descriptio) {
       this.code = code;
       this.descriptio = descriptio;
    }
   
     @Id 
    
    @Column(name="code", unique=true, nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="descriptio", nullable=false, length=65535)
    public String getDescriptio() {
        return this.descriptio;
    }
    
    public void setDescriptio(String descriptio) {
        this.descriptio = descriptio;
    }




}


