package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dosage generated by hbm2java
 */
@Entity
@Table(name="dosage"
    ,catalog="extended"
)
public class Dosage  implements java.io.Serializable {


     private Integer dosageId;
     private InventoryItems inventoryItems;
     private String shortCode;
     private String description;
     private int quantity;
     private Set<Patienttreatment> patienttreatments = new HashSet<Patienttreatment>(0);

    public Dosage() {
    }

	
    public Dosage(InventoryItems inventoryItems, String shortCode, String description, int quantity) {
        this.inventoryItems = inventoryItems;
        this.shortCode = shortCode;
        this.description = description;
        this.quantity = quantity;
    }
    public Dosage(InventoryItems inventoryItems, String shortCode, String description, int quantity, Set<Patienttreatment> patienttreatments) {
       this.inventoryItems = inventoryItems;
       this.shortCode = shortCode;
       this.description = description;
       this.quantity = quantity;
       this.patienttreatments = patienttreatments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="dosage_id", unique=true, nullable=false)
    public Integer getDosageId() {
        return this.dosageId;
    }
    
    public void setDosageId(Integer dosageId) {
        this.dosageId = dosageId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_code", nullable=false)
    public InventoryItems getInventoryItems() {
        return this.inventoryItems;
    }
    
    public void setInventoryItems(InventoryItems inventoryItems) {
        this.inventoryItems = inventoryItems;
    }
    
    @Column(name="short_code", nullable=false, length=10)
    public String getShortCode() {
        return this.shortCode;
    }
    
    public void setShortCode(String shortCode) {
        this.shortCode = shortCode;
    }
    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dosage")
    public Set<Patienttreatment> getPatienttreatments() {
        return this.patienttreatments;
    }
    
    public void setPatienttreatments(Set<Patienttreatment> patienttreatments) {
        this.patienttreatments = patienttreatments;
    }




}


