package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DurationOptions generated by hbm2java
 */
@Entity
@Table(name="duration_options"
    ,catalog="extended"
)
public class DurationOptions  implements java.io.Serializable {


     private Integer durationId;
     private String duration;

    public DurationOptions() {
    }

    public DurationOptions(String duration) {
       this.duration = duration;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="duration_id", unique=true, nullable=false)
    public Integer getDurationId() {
        return this.durationId;
    }
    
    public void setDurationId(Integer durationId) {
        this.durationId = durationId;
    }
    
    @Column(name="duration", nullable=false)
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }




}


