package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Facility generated by hbm2java
 */
@Entity
@Table(name="facility"
    ,catalog="extended"
)
public class Facility  implements java.io.Serializable {


     private Integer id;
     private String doctorIncharge;
     private String facilityName;

    public Facility() {
    }

    public Facility(String doctorIncharge, String facilityName) {
       this.doctorIncharge = doctorIncharge;
       this.facilityName = facilityName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="doctor_incharge", nullable=false, length=65535)
    public String getDoctorIncharge() {
        return this.doctorIncharge;
    }
    
    public void setDoctorIncharge(String doctorIncharge) {
        this.doctorIncharge = doctorIncharge;
    }
    
    @Column(name="facility_name", nullable=false, length=65535)
    public String getFacilityName() {
        return this.facilityName;
    }
    
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName;
    }




}


