package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FolderNumbering generated by hbm2java
 */
@Entity
@Table(name="folder_numbering"
    ,catalog="extended"
)
public class FolderNumbering  implements java.io.Serializable {


     private Integer numberingId;
     private String folderAbbreviationClinic;
     private String folderAbbreviationDiagnostics;
     private String folderAbbreviationPharmacy;
     private int clinicStartNumber;
     private int diagnosticStartNumber;
     private int pharmacyStartNumber;
     private int clinicCounter;
     private int diagnosticCounter;
     private int pharmacyCounter;

    public FolderNumbering() {
    }

    public FolderNumbering(String folderAbbreviationClinic, String folderAbbreviationDiagnostics, String folderAbbreviationPharmacy, int clinicStartNumber, int diagnosticStartNumber, int pharmacyStartNumber, int clinicCounter, int diagnosticCounter, int pharmacyCounter) {
       this.folderAbbreviationClinic = folderAbbreviationClinic;
       this.folderAbbreviationDiagnostics = folderAbbreviationDiagnostics;
       this.folderAbbreviationPharmacy = folderAbbreviationPharmacy;
       this.clinicStartNumber = clinicStartNumber;
       this.diagnosticStartNumber = diagnosticStartNumber;
       this.pharmacyStartNumber = pharmacyStartNumber;
       this.clinicCounter = clinicCounter;
       this.diagnosticCounter = diagnosticCounter;
       this.pharmacyCounter = pharmacyCounter;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="numbering_id", unique=true, nullable=false)
    public Integer getNumberingId() {
        return this.numberingId;
    }
    
    public void setNumberingId(Integer numberingId) {
        this.numberingId = numberingId;
    }
    
    @Column(name="folder_abbreviation_clinic", nullable=false, length=65535)
    public String getFolderAbbreviationClinic() {
        return this.folderAbbreviationClinic;
    }
    
    public void setFolderAbbreviationClinic(String folderAbbreviationClinic) {
        this.folderAbbreviationClinic = folderAbbreviationClinic;
    }
    
    @Column(name="folder_abbreviation_diagnostics", nullable=false, length=65535)
    public String getFolderAbbreviationDiagnostics() {
        return this.folderAbbreviationDiagnostics;
    }
    
    public void setFolderAbbreviationDiagnostics(String folderAbbreviationDiagnostics) {
        this.folderAbbreviationDiagnostics = folderAbbreviationDiagnostics;
    }
    
    @Column(name="folder_abbreviation_pharmacy", nullable=false, length=65535)
    public String getFolderAbbreviationPharmacy() {
        return this.folderAbbreviationPharmacy;
    }
    
    public void setFolderAbbreviationPharmacy(String folderAbbreviationPharmacy) {
        this.folderAbbreviationPharmacy = folderAbbreviationPharmacy;
    }
    
    @Column(name="clinic_start_number", nullable=false)
    public int getClinicStartNumber() {
        return this.clinicStartNumber;
    }
    
    public void setClinicStartNumber(int clinicStartNumber) {
        this.clinicStartNumber = clinicStartNumber;
    }
    
    @Column(name="diagnostic_start_number", nullable=false)
    public int getDiagnosticStartNumber() {
        return this.diagnosticStartNumber;
    }
    
    public void setDiagnosticStartNumber(int diagnosticStartNumber) {
        this.diagnosticStartNumber = diagnosticStartNumber;
    }
    
    @Column(name="pharmacy_start_number", nullable=false)
    public int getPharmacyStartNumber() {
        return this.pharmacyStartNumber;
    }
    
    public void setPharmacyStartNumber(int pharmacyStartNumber) {
        this.pharmacyStartNumber = pharmacyStartNumber;
    }
    
    @Column(name="clinic_counter", nullable=false)
    public int getClinicCounter() {
        return this.clinicCounter;
    }
    
    public void setClinicCounter(int clinicCounter) {
        this.clinicCounter = clinicCounter;
    }
    
    @Column(name="diagnostic_counter", nullable=false)
    public int getDiagnosticCounter() {
        return this.diagnosticCounter;
    }
    
    public void setDiagnosticCounter(int diagnosticCounter) {
        this.diagnosticCounter = diagnosticCounter;
    }
    
    @Column(name="pharmacy_counter", nullable=false)
    public int getPharmacyCounter() {
        return this.pharmacyCounter;
    }
    
    public void setPharmacyCounter(int pharmacyCounter) {
        this.pharmacyCounter = pharmacyCounter;
    }




}


