package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Folder generated by hbm2java
 */
@Entity
@Table(name="folder"
    ,catalog="extended"
)
public class Folder  implements java.io.Serializable {


     private String foldernumber;
     private String shelvenumber;
     private String status;
     private String previouslocation;

    public Folder() {
    }

	
    public Folder(String foldernumber) {
        this.foldernumber = foldernumber;
    }
    public Folder(String foldernumber, String shelvenumber, String status, String previouslocation) {
       this.foldernumber = foldernumber;
       this.shelvenumber = shelvenumber;
       this.status = status;
       this.previouslocation = previouslocation;
    }
   
     @Id 
    
    @Column(name="foldernumber", unique=true, nullable=false, length=50)
    public String getFoldernumber() {
        return this.foldernumber;
    }
    
    public void setFoldernumber(String foldernumber) {
        this.foldernumber = foldernumber;
    }
    
    @Column(name="shelvenumber", length=100)
    public String getShelvenumber() {
        return this.shelvenumber;
    }
    
    public void setShelvenumber(String shelvenumber) {
        this.shelvenumber = shelvenumber;
    }
    
    @Column(name="status", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="previouslocation")
    public String getPreviouslocation() {
        return this.previouslocation;
    }
    
    public void setPreviouslocation(String previouslocation) {
        this.previouslocation = previouslocation;
    }




}


