package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GeneralSettings generated by hbm2java
 */
@Entity
@Table(name="general_settings"
    ,catalog="extended"
)
public class GeneralSettings  implements java.io.Serializable {


     private Integer id;
     private String name;
     private boolean value;
     private Date dateAdded;
     private String staffId;

    public GeneralSettings() {
    }

    public GeneralSettings(String name, boolean value, Date dateAdded, String staffId) {
       this.name = name;
       this.value = value;
       this.dateAdded = dateAdded;
       this.staffId = staffId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="value", nullable=false)
    public boolean isValue() {
        return this.value;
    }
    
    public void setValue(boolean value) {
        this.value = value;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_added", nullable=false, length=19)
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    
    @Column(name="staff_id", nullable=false, length=100)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }




}


