package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InPatientBills generated by hbm2java
 */
@Entity
@Table(name="in_patient_bills"
    ,catalog="extended"
)
public class InPatientBills  implements java.io.Serializable {


     private int visitid;
     private String patientid;
     private double totalBill;
     private double amountPaid;
     private String status;

    public InPatientBills() {
    }

    public InPatientBills(int visitid, String patientid, double totalBill, double amountPaid, String status) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.totalBill = totalBill;
       this.amountPaid = amountPaid;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="visitid", unique=true, nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="patientid", nullable=false, length=65535)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="total_bill", nullable=false, precision=22, scale=0)
    public double getTotalBill() {
        return this.totalBill;
    }
    
    public void setTotalBill(double totalBill) {
        this.totalBill = totalBill;
    }
    
    @Column(name="amount_paid", nullable=false, precision=22, scale=0)
    public double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(double amountPaid) {
        this.amountPaid = amountPaid;
    }
    
    @Column(name="status", nullable=false, length=65535)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


