package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InvestigationAntibiotic generated by hbm2java
 */
@Entity
@Table(name="investigation_antibiotic"
    ,catalog="extended"
)
public class InvestigationAntibiotic  implements java.io.Serializable {


     private Integer id;
     private int invId;
     private int antibioticId;
     private String status;

    public InvestigationAntibiotic() {
    }

    public InvestigationAntibiotic(int invId, int antibioticId, String status) {
       this.invId = invId;
       this.antibioticId = antibioticId;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="inv_id", nullable=false)
    public int getInvId() {
        return this.invId;
    }
    
    public void setInvId(int invId) {
        this.invId = invId;
    }
    
    @Column(name="antibiotic_id", nullable=false)
    public int getAntibioticId() {
        return this.antibioticId;
    }
    
    public void setAntibioticId(int antibioticId) {
        this.antibioticId = antibioticId;
    }
    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


