package entities;
// Generated Nov 25, 2013 10:35:09 AM by Hibernate Tools 3.2.1.GA



/**
 * InventoryLog generated by hbm2java
 */
public class InventoryLog  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String batchno;
     private String transactiontype;
     private int quantitytransferred;

    public InventoryLog() {
    }

    public InventoryLog(String code, String batchno, String transactiontype, int quantitytransferred) {
       this.code = code;
       this.batchno = batchno;
       this.transactiontype = transactiontype;
       this.quantitytransferred = quantitytransferred;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBatchno() {
        return this.batchno;
    }
    
    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }
    public String getTransactiontype() {
        return this.transactiontype;
    }
    
    public void setTransactiontype(String transactiontype) {
        this.transactiontype = transactiontype;
    }
    public int getQuantitytransferred() {
        return this.quantitytransferred;
    }
    
    public void setQuantitytransferred(int quantitytransferred) {
        this.quantitytransferred = quantitytransferred;
    }




}


