package entities;
// Generated Nov 25, 2013 10:35:09 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * InventoryTransfers generated by hbm2java
 */
public class InventoryTransfers  implements java.io.Serializable {


     private Integer requisitionid;
     private String itemcode;
     private String orderer;
     private Date orderdate;
     private Date deliverydate;
     private String deliverer;
     private String status;
     private String unit;
     private int requestedquantity;
     private int deliveredquantity;
     private String batchNo;

    public InventoryTransfers() {
    }

	
    public InventoryTransfers(String itemcode, String orderer, Date orderdate, String status, String unit, int requestedquantity, int deliveredquantity, String batchNo) {
        this.itemcode = itemcode;
        this.orderer = orderer;
        this.orderdate = orderdate;
        this.status = status;
        this.unit = unit;
        this.requestedquantity = requestedquantity;
        this.deliveredquantity = deliveredquantity;
        this.batchNo = batchNo;
    }
    public InventoryTransfers(String itemcode, String orderer, Date orderdate, Date deliverydate, String deliverer, String status, String unit, int requestedquantity, int deliveredquantity, String batchNo) {
       this.itemcode = itemcode;
       this.orderer = orderer;
       this.orderdate = orderdate;
       this.deliverydate = deliverydate;
       this.deliverer = deliverer;
       this.status = status;
       this.unit = unit;
       this.requestedquantity = requestedquantity;
       this.deliveredquantity = deliveredquantity;
       this.batchNo = batchNo;
    }
   
    public Integer getRequisitionid() {
        return this.requisitionid;
    }
    
    public void setRequisitionid(Integer requisitionid) {
        this.requisitionid = requisitionid;
    }
    public String getItemcode() {
        return this.itemcode;
    }
    
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }
    public String getOrderer() {
        return this.orderer;
    }
    
    public void setOrderer(String orderer) {
        this.orderer = orderer;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    public Date getDeliverydate() {
        return this.deliverydate;
    }
    
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }
    public String getDeliverer() {
        return this.deliverer;
    }
    
    public void setDeliverer(String deliverer) {
        this.deliverer = deliverer;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public int getRequestedquantity() {
        return this.requestedquantity;
    }
    
    public void setRequestedquantity(int requestedquantity) {
        this.requestedquantity = requestedquantity;
    }
    public int getDeliveredquantity() {
        return this.deliveredquantity;
    }
    
    public void setDeliveredquantity(int deliveredquantity) {
        this.deliveredquantity = deliveredquantity;
    }
    public String getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }




}


