package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemForm generated by hbm2java
 */
@Entity
@Table(name="item_form"
    ,catalog="extended"
)
public class ItemForm  implements java.io.Serializable {


     private Integer formId;
     private String formDescription;
     private Set<PharmacyItem> pharmacyItems = new HashSet<PharmacyItem>(0);
     private Set<InventoryItems> inventoryItemses = new HashSet<InventoryItems>(0);
     private Set<LaboratoryItem> laboratoryItems = new HashSet<LaboratoryItem>(0);
     private Set<DispensaryItems> dispensaryItemses = new HashSet<DispensaryItems>(0);

    public ItemForm() {
    }

	
    public ItemForm(String formDescription) {
        this.formDescription = formDescription;
    }
    public ItemForm(String formDescription, Set<PharmacyItem> pharmacyItems, Set<InventoryItems> inventoryItemses, Set<LaboratoryItem> laboratoryItems, Set<DispensaryItems> dispensaryItemses) {
       this.formDescription = formDescription;
       this.pharmacyItems = pharmacyItems;
       this.inventoryItemses = inventoryItemses;
       this.laboratoryItems = laboratoryItems;
       this.dispensaryItemses = dispensaryItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="form_id", unique=true, nullable=false)
    public Integer getFormId() {
        return this.formId;
    }
    
    public void setFormId(Integer formId) {
        this.formId = formId;
    }
    
    @Column(name="form_description", nullable=false)
    public String getFormDescription() {
        return this.formDescription;
    }
    
    public void setFormDescription(String formDescription) {
        this.formDescription = formDescription;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itemForm")
    public Set<PharmacyItem> getPharmacyItems() {
        return this.pharmacyItems;
    }
    
    public void setPharmacyItems(Set<PharmacyItem> pharmacyItems) {
        this.pharmacyItems = pharmacyItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itemForm")
    public Set<InventoryItems> getInventoryItemses() {
        return this.inventoryItemses;
    }
    
    public void setInventoryItemses(Set<InventoryItems> inventoryItemses) {
        this.inventoryItemses = inventoryItemses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itemForm")
    public Set<LaboratoryItem> getLaboratoryItems() {
        return this.laboratoryItems;
    }
    
    public void setLaboratoryItems(Set<LaboratoryItem> laboratoryItems) {
        this.laboratoryItems = laboratoryItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itemForm")
    public Set<DispensaryItems> getDispensaryItemses() {
        return this.dispensaryItemses;
    }
    
    public void setDispensaryItemses(Set<DispensaryItems> dispensaryItemses) {
        this.dispensaryItemses = dispensaryItemses;
    }




}


