package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Itemtype generated by hbm2java
 */
@Entity
@Table(name="itemtype"
    ,catalog="extended"
)
public class Itemtype  implements java.io.Serializable {


     private String id;
     private String itemType;

    public Itemtype() {
    }

	
    public Itemtype(String id) {
        this.id = id;
    }
    public Itemtype(String id, String itemType) {
       this.id = id;
       this.itemType = itemType;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=100)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="itemType", length=100)
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }




}


