package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LabAntibiotic generated by hbm2java
 */
@Entity
@Table(name="lab_antibiotic"
    ,catalog="extended"
)
public class LabAntibiotic  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer orderNum;

    public LabAntibiotic() {
    }

	
    public LabAntibiotic(String name) {
        this.name = name;
    }
    public LabAntibiotic(String name, Integer orderNum) {
       this.name = name;
       this.orderNum = orderNum;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="order_num")
    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }




}


