package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LabDiscount generated by hbm2java
 */
@Entity
@Table(name="lab_discount"
    ,catalog="extended"
)
public class LabDiscount  implements java.io.Serializable {


     private Integer discountId;
     private String labId;
     private String patientId;
     private double percentageDiscount;
     private double discounted;
     private double newAmount;
     private String staffId;
     private String status;
     private String reason;

    public LabDiscount() {
    }

    public LabDiscount(String labId, String patientId, double percentageDiscount, double discounted, double newAmount, String staffId, String status, String reason) {
       this.labId = labId;
       this.patientId = patientId;
       this.percentageDiscount = percentageDiscount;
       this.discounted = discounted;
       this.newAmount = newAmount;
       this.staffId = staffId;
       this.status = status;
       this.reason = reason;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="discount_id", unique=true, nullable=false)
    public Integer getDiscountId() {
        return this.discountId;
    }
    
    public void setDiscountId(Integer discountId) {
        this.discountId = discountId;
    }
    
    @Column(name="lab_id", nullable=false, length=65535)
    public String getLabId() {
        return this.labId;
    }
    
    public void setLabId(String labId) {
        this.labId = labId;
    }
    
    @Column(name="patient_id", nullable=false, length=65535)
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    
    @Column(name="percentage_discount", nullable=false, precision=22, scale=0)
    public double getPercentageDiscount() {
        return this.percentageDiscount;
    }
    
    public void setPercentageDiscount(double percentageDiscount) {
        this.percentageDiscount = percentageDiscount;
    }
    
    @Column(name="discounted", nullable=false, precision=22, scale=0)
    public double getDiscounted() {
        return this.discounted;
    }
    
    public void setDiscounted(double discounted) {
        this.discounted = discounted;
    }
    
    @Column(name="new_amount", nullable=false, precision=22, scale=0)
    public double getNewAmount() {
        return this.newAmount;
    }
    
    public void setNewAmount(double newAmount) {
        this.newAmount = newAmount;
    }
    
    @Column(name="staff_id", nullable=false, length=65535)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    
    @Column(name="status", nullable=false, length=65535)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="reason", nullable=false, length=65535)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


