package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LabPatient generated by hbm2java
 */
@Entity
@Table(name="lab_patient"
    ,catalog="extended"
)
public class LabPatient  implements java.io.Serializable {


     private String patientid;
     private String fname;
     private String lname;
     private String midname;
     private String gender;
     private String address;
     private String employer;
     private Date dateofbirth;
     private String contact;
     private String emergencyperson;
     private String emergencycontact;
     private String email;
     private Date dateofregistration;
     private String country;
     private String city;
     private String maritalstatus;
     private String imglocation;
     private int lastVisitId;
     private Integer lastClaimId;
     private String folderNumber;

    public LabPatient() {
    }

	
    public LabPatient(String patientid, int lastVisitId, String folderNumber) {
        this.patientid = patientid;
        this.lastVisitId = lastVisitId;
        this.folderNumber = folderNumber;
    }
    public LabPatient(String patientid, String fname, String lname, String midname, String gender, String address, String employer, Date dateofbirth, String contact, String emergencyperson, String emergencycontact, String email, Date dateofregistration, String country, String city, String maritalstatus, String imglocation, int lastVisitId, Integer lastClaimId, String folderNumber) {
       this.patientid = patientid;
       this.fname = fname;
       this.lname = lname;
       this.midname = midname;
       this.gender = gender;
       this.address = address;
       this.employer = employer;
       this.dateofbirth = dateofbirth;
       this.contact = contact;
       this.emergencyperson = emergencyperson;
       this.emergencycontact = emergencycontact;
       this.email = email;
       this.dateofregistration = dateofregistration;
       this.country = country;
       this.city = city;
       this.maritalstatus = maritalstatus;
       this.imglocation = imglocation;
       this.lastVisitId = lastVisitId;
       this.lastClaimId = lastClaimId;
       this.folderNumber = folderNumber;
    }
   
     @Id 
    
    @Column(name="patientid", unique=true, nullable=false, length=50)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="fname", length=100)
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    
    @Column(name="lname", length=100)
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    
    @Column(name="midname", length=100)
    public String getMidname() {
        return this.midname;
    }
    
    public void setMidname(String midname) {
        this.midname = midname;
    }
    
    @Column(name="gender", length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="employer", length=100)
    public String getEmployer() {
        return this.employer;
    }
    
    public void setEmployer(String employer) {
        this.employer = employer;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateofbirth", length=10)
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    
    @Column(name="contact", length=100)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    
    @Column(name="emergencyperson", length=100)
    public String getEmergencyperson() {
        return this.emergencyperson;
    }
    
    public void setEmergencyperson(String emergencyperson) {
        this.emergencyperson = emergencyperson;
    }
    
    @Column(name="emergencycontact", length=100)
    public String getEmergencycontact() {
        return this.emergencycontact;
    }
    
    public void setEmergencycontact(String emergencycontact) {
        this.emergencycontact = emergencycontact;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateofregistration", length=19)
    public Date getDateofregistration() {
        return this.dateofregistration;
    }
    
    public void setDateofregistration(Date dateofregistration) {
        this.dateofregistration = dateofregistration;
    }
    
    @Column(name="country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="maritalstatus")
    public String getMaritalstatus() {
        return this.maritalstatus;
    }
    
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }
    
    @Column(name="imglocation")
    public String getImglocation() {
        return this.imglocation;
    }
    
    public void setImglocation(String imglocation) {
        this.imglocation = imglocation;
    }
    
    @Column(name="last_visit_id", nullable=false)
    public int getLastVisitId() {
        return this.lastVisitId;
    }
    
    public void setLastVisitId(int lastVisitId) {
        this.lastVisitId = lastVisitId;
    }
    
    @Column(name="last_claim_id")
    public Integer getLastClaimId() {
        return this.lastClaimId;
    }
    
    public void setLastClaimId(Integer lastClaimId) {
        this.lastClaimId = lastClaimId;
    }
    
    @Column(name="folder_number", nullable=false, length=50)
    public String getFolderNumber() {
        return this.folderNumber;
    }
    
    public void setFolderNumber(String folderNumber) {
        this.folderNumber = folderNumber;
    }




}


