package entities;
// Generated Nov 25, 2013 10:35:09 AM by Hibernate Tools 3.2.1.GA



/**
 * LabStockItemDistributor generated by hbm2java
 */
public class LabStockItemDistributor  implements java.io.Serializable {


     private Integer id;
     private int itemId;
     private int distributorId;
     private double currentLevel;
     private double spentLevel;
     private double totalLevel;

    public LabStockItemDistributor() {
    }

    public LabStockItemDistributor(int itemId, int distributorId, double currentLevel, double spentLevel, double totalLevel) {
       this.itemId = itemId;
       this.distributorId = distributorId;
       this.currentLevel = currentLevel;
       this.spentLevel = spentLevel;
       this.totalLevel = totalLevel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public int getDistributorId() {
        return this.distributorId;
    }
    
    public void setDistributorId(int distributorId) {
        this.distributorId = distributorId;
    }
    public double getCurrentLevel() {
        return this.currentLevel;
    }
    
    public void setCurrentLevel(double currentLevel) {
        this.currentLevel = currentLevel;
    }
    public double getSpentLevel() {
        return this.spentLevel;
    }
    
    public void setSpentLevel(double spentLevel) {
        this.spentLevel = spentLevel;
    }
    public double getTotalLevel() {
        return this.totalLevel;
    }
    
    public void setTotalLevel(double totalLevel) {
        this.totalLevel = totalLevel;
    }




}


