package entities;
// Generated Nov 25, 2013 10:35:09 AM by Hibernate Tools 3.2.1.GA



/**
 * LabStockDistributor generated by hbm2java
 */
public class LabStockDistributor  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String contactPerson;
     private String phone;
     private String location;

    public LabStockDistributor() {
    }

    public LabStockDistributor(String name, String contactPerson, String phone, String location) {
       this.name = name;
       this.contactPerson = contactPerson;
       this.phone = phone;
       this.location = location;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


