package entities;
// Generated Nov 25, 2013 10:35:09 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LabStockItem generated by hbm2java
 */
public class LabStockItem  implements java.io.Serializable {


     private String id;
     private String name;
     private int reOrderLevel;
     private String markUp;
     private int emergencyStockLevel;
     private int maximumStockLevel;
     private int quantity;
     private String staffId;
     private Date dateAdded;

    public LabStockItem() {
    }

    public LabStockItem(String id, String name, int reOrderLevel, String markUp, int emergencyStockLevel, int maximumStockLevel, int quantity, String staffId, Date dateAdded) {
       this.id = id;
       this.name = name;
       this.reOrderLevel = reOrderLevel;
       this.markUp = markUp;
       this.emergencyStockLevel = emergencyStockLevel;
       this.maximumStockLevel = maximumStockLevel;
       this.quantity = quantity;
       this.staffId = staffId;
       this.dateAdded = dateAdded;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getReOrderLevel() {
        return this.reOrderLevel;
    }
    
    public void setReOrderLevel(int reOrderLevel) {
        this.reOrderLevel = reOrderLevel;
    }
    public String getMarkUp() {
        return this.markUp;
    }
    
    public void setMarkUp(String markUp) {
        this.markUp = markUp;
    }
    public int getEmergencyStockLevel() {
        return this.emergencyStockLevel;
    }
    
    public void setEmergencyStockLevel(int emergencyStockLevel) {
        this.emergencyStockLevel = emergencyStockLevel;
    }
    public int getMaximumStockLevel() {
        return this.maximumStockLevel;
    }
    
    public void setMaximumStockLevel(int maximumStockLevel) {
        this.maximumStockLevel = maximumStockLevel;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }




}


