package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Labtypes generated by hbm2java
 */
@Entity
@Table(name="labtypes"
    ,catalog="extended"
)
public class Labtypes  implements java.io.Serializable {


     private Integer labTypeId;
     private String labCode;
     private String labType;
     private Integer orderNum;
     private int active;

    public Labtypes() {
    }

	
    public Labtypes(String labCode, String labType, int active) {
        this.labCode = labCode;
        this.labType = labType;
        this.active = active;
    }
    public Labtypes(String labCode, String labType, Integer orderNum, int active) {
       this.labCode = labCode;
       this.labType = labType;
       this.orderNum = orderNum;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="lab_type_id", unique=true, nullable=false)
    public Integer getLabTypeId() {
        return this.labTypeId;
    }
    
    public void setLabTypeId(Integer labTypeId) {
        this.labTypeId = labTypeId;
    }
    
    @Column(name="lab_code", nullable=false, length=10)
    public String getLabCode() {
        return this.labCode;
    }
    
    public void setLabCode(String labCode) {
        this.labCode = labCode;
    }
    
    @Column(name="lab_type", nullable=false, length=225)
    public String getLabType() {
        return this.labType;
    }
    
    public void setLabType(String labType) {
        this.labType = labType;
    }
    
    @Column(name="order_num")
    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


