package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Loggingtable generated by hbm2java
 */
@Entity
@Table(name="loggingtable"
    ,catalog="extended"
)
public class Loggingtable  implements java.io.Serializable {


     private Integer id;
     private String userid;
     private Date logintime;
     private Date logoutitme;
     private String action;
     private Date date;

    public Loggingtable() {
    }

	
    public Loggingtable(String userid, String action, Date date) {
        this.userid = userid;
        this.action = action;
        this.date = date;
    }
    public Loggingtable(String userid, Date logintime, Date logoutitme, String action, Date date) {
       this.userid = userid;
       this.logintime = logintime;
       this.logoutitme = logoutitme;
       this.action = action;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="userid", nullable=false, length=200)
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="logintime", length=8)
    public Date getLogintime() {
        return this.logintime;
    }
    
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="logoutitme", length=8)
    public Date getLogoutitme() {
        return this.logoutitme;
    }
    
    public void setLogoutitme(Date logoutitme) {
        this.logoutitme = logoutitme;
    }
    
    @Column(name="action", nullable=false, length=65535)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


