package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MaininvSubinv generated by hbm2java
 */
@Entity
@Table(name="maininv_subinv"
    ,catalog="extended"
)
public class MaininvSubinv  implements java.io.Serializable {


     private Integer maininvSubinvId;
     private int maininvId;
     private int subinvId;

    public MaininvSubinv() {
    }

    public MaininvSubinv(int maininvId, int subinvId) {
       this.maininvId = maininvId;
       this.subinvId = subinvId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="maininv_subinv_id", unique=true, nullable=false)
    public Integer getMaininvSubinvId() {
        return this.maininvSubinvId;
    }
    
    public void setMaininvSubinvId(Integer maininvSubinvId) {
        this.maininvSubinvId = maininvSubinvId;
    }
    
    @Column(name="maininv_id", nullable=false)
    public int getMaininvId() {
        return this.maininvId;
    }
    
    public void setMaininvId(int maininvId) {
        this.maininvId = maininvId;
    }
    
    @Column(name="subinv_id", nullable=false)
    public int getSubinvId() {
        return this.subinvId;
    }
    
    public void setSubinvId(int subinvId) {
        this.subinvId = subinvId;
    }




}


