package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manufacturer generated by hbm2java
 */
@Entity
@Table(name="manufacturer"
    ,catalog="extended"
)
public class Manufacturer  implements java.io.Serializable {


     private Integer manufacturerid;
     private String manufaturer;
     private String telephone;
     private String address;
     private String email;

    public Manufacturer() {
    }

	
    public Manufacturer(String manufaturer) {
        this.manufaturer = manufaturer;
    }
    public Manufacturer(String manufaturer, String telephone, String address, String email) {
       this.manufaturer = manufaturer;
       this.telephone = telephone;
       this.address = address;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="manufacturerid", unique=true, nullable=false)
    public Integer getManufacturerid() {
        return this.manufacturerid;
    }
    
    public void setManufacturerid(Integer manufacturerid) {
        this.manufacturerid = manufacturerid;
    }
    
    @Column(name="manufaturer", nullable=false, length=65535)
    public String getManufaturer() {
        return this.manufaturer;
    }
    
    public void setManufaturer(String manufaturer) {
        this.manufaturer = manufaturer;
    }
    
    @Column(name="telephone", length=65535)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    @Column(name="address", length=65535)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="email", length=65535)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


