package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MedicalHistories generated by hbm2java
 */
@Entity
@Table(name="medical_histories"
    ,catalog="extended"
)
public class MedicalHistories  implements java.io.Serializable {


     private Integer historyId;
     private String history;

    public MedicalHistories() {
    }

    public MedicalHistories(String history) {
       this.history = history;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="history_id", unique=true, nullable=false)
    public Integer getHistoryId() {
        return this.historyId;
    }
    
    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }
    
    @Column(name="history", nullable=false)
    public String getHistory() {
        return this.history;
    }
    
    public void setHistory(String history) {
        this.history = history;
    }




}


