package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Newborn generated by hbm2java
 */
@Entity
@Table(name="newborn"
    ,catalog="extended"
)
public class Newborn  implements java.io.Serializable {


     private Integer newbordid;
     private Date year;
     private String month;
     private String day;
     private Date time;
     private String momsid;
     private String supervisingmidwife;
     private String complications;

    public Newborn() {
    }

	
    public Newborn(Date year, String month, String day, Date time, String momsid) {
        this.year = year;
        this.month = month;
        this.day = day;
        this.time = time;
        this.momsid = momsid;
    }
    public Newborn(Date year, String month, String day, Date time, String momsid, String supervisingmidwife, String complications) {
       this.year = year;
       this.month = month;
       this.day = day;
       this.time = time;
       this.momsid = momsid;
       this.supervisingmidwife = supervisingmidwife;
       this.complications = complications;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="newbordid", unique=true, nullable=false)
    public Integer getNewbordid() {
        return this.newbordid;
    }
    
    public void setNewbordid(Integer newbordid) {
        this.newbordid = newbordid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year", nullable=false, length=0)
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }
    
    @Column(name="month", nullable=false, length=3)
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    
    @Column(name="day", nullable=false, length=3)
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="time", nullable=false, length=8)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    
    @Column(name="momsid", nullable=false)
    public String getMomsid() {
        return this.momsid;
    }
    
    public void setMomsid(String momsid) {
        this.momsid = momsid;
    }
    
    @Column(name="supervisingmidwife")
    public String getSupervisingmidwife() {
        return this.supervisingmidwife;
    }
    
    public void setSupervisingmidwife(String supervisingmidwife) {
        this.supervisingmidwife = supervisingmidwife;
    }
    
    @Column(name="complications")
    public String getComplications() {
        return this.complications;
    }
    
    public void setComplications(String complications) {
        this.complications = complications;
    }




}


