package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nhistreatment generated by hbm2java
 */
@Entity
@Table(name="nhistreatment"
    ,catalog="extended"
)
public class Nhistreatment  implements java.io.Serializable {


     private Integer treatmentid;
     private String medicine;
     private String unitPrice;
     private double price;
     private String gdrg;
     private int therapeuticGroup;
     private String diagnosticgroup;

    public Nhistreatment() {
    }

    public Nhistreatment(String medicine, String unitPrice, double price, String gdrg, int therapeuticGroup, String diagnosticgroup) {
       this.medicine = medicine;
       this.unitPrice = unitPrice;
       this.price = price;
       this.gdrg = gdrg;
       this.therapeuticGroup = therapeuticGroup;
       this.diagnosticgroup = diagnosticgroup;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="treatmentid", unique=true, nullable=false)
    public Integer getTreatmentid() {
        return this.treatmentid;
    }
    
    public void setTreatmentid(Integer treatmentid) {
        this.treatmentid = treatmentid;
    }
    
    @Column(name="medicine", nullable=false, length=1000)
    public String getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }
    
    @Column(name="unit_price", nullable=false, length=20)
    public String getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    
    @Column(name="gdrg", nullable=false, length=25)
    public String getGdrg() {
        return this.gdrg;
    }
    
    public void setGdrg(String gdrg) {
        this.gdrg = gdrg;
    }
    
    @Column(name="therapeutic_group", nullable=false)
    public int getTherapeuticGroup() {
        return this.therapeuticGroup;
    }
    
    public void setTherapeuticGroup(int therapeuticGroup) {
        this.therapeuticGroup = therapeuticGroup;
    }
    
    @Column(name="diagnosticgroup", nullable=false, length=10)
    public String getDiagnosticgroup() {
        return this.diagnosticgroup;
    }
    
    public void setDiagnosticgroup(String diagnosticgroup) {
        this.diagnosticgroup = diagnosticgroup;
    }




}


