package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NursingtableVitals generated by hbm2java
 */
@Entity
@Table(name="nursingtable_vitals"
    ,catalog="extended"
)
public class NursingtableVitals  implements java.io.Serializable {


     private Integer id;
     private int visitId;
     private String staffId;
     private String docId;
     private Date time;

    public NursingtableVitals() {
    }

	
    public NursingtableVitals(int visitId, String staffId, Date time) {
        this.visitId = visitId;
        this.staffId = staffId;
        this.time = time;
    }
    public NursingtableVitals(int visitId, String staffId, String docId, Date time) {
       this.visitId = visitId;
       this.staffId = staffId;
       this.docId = docId;
       this.time = time;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="visit_id", nullable=false)
    public int getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(int visitId) {
        this.visitId = visitId;
    }
    
    @Column(name="staff_id", nullable=false, length=50)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    
    @Column(name="doc_id", length=50)
    public String getDocId() {
        return this.docId;
    }
    
    public void setDocId(String docId) {
        this.docId = docId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time", nullable=false, length=19)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


