package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NursesPatientReliefs generated by hbm2java
 */
@Entity
@Table(name="nurses_patient_reliefs"
    ,catalog="extended"
)
public class NursesPatientReliefs  implements java.io.Serializable {


     private Integer id;
     private int reliefId;
     private String patientid;
     private int visitid;
     private String seenby;

    public NursesPatientReliefs() {
    }

    public NursesPatientReliefs(int reliefId, String patientid, int visitid, String seenby) {
       this.reliefId = reliefId;
       this.patientid = patientid;
       this.visitid = visitid;
       this.seenby = seenby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="relief_id", nullable=false)
    public int getReliefId() {
        return this.reliefId;
    }
    
    public void setReliefId(int reliefId) {
        this.reliefId = reliefId;
    }
    
    @Column(name="patientid", nullable=false, length=10)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="seenby", nullable=false)
    public String getSeenby() {
        return this.seenby;
    }
    
    public void setSeenby(String seenby) {
        this.seenby = seenby;
    }




}


