package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NursesPatientConditions generated by hbm2java
 */
@Entity
@Table(name="nurses_patient_conditions"
    ,catalog="extended"
)
public class NursesPatientConditions  implements java.io.Serializable {


     private Integer id;
     private int conditionId;
     private int visitid;
     private String patientid;
     private String seenby;

    public NursesPatientConditions() {
    }

    public NursesPatientConditions(int conditionId, int visitid, String patientid, String seenby) {
       this.conditionId = conditionId;
       this.visitid = visitid;
       this.patientid = patientid;
       this.seenby = seenby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="condition_id", nullable=false)
    public int getConditionId() {
        return this.conditionId;
    }
    
    public void setConditionId(int conditionId) {
        this.conditionId = conditionId;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="patientid", nullable=false, length=11)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="seenby", nullable=false)
    public String getSeenby() {
        return this.seenby;
    }
    
    public void setSeenby(String seenby) {
        this.seenby = seenby;
    }




}


