package entities;
// Generated Nov 15, 2013 8:19:17 PM by Hibernate Tools 3.2.1.GA



/**
 * Orderitems generated by hbm2java
 */
public class Orderitems  implements java.io.Serializable {


     private Integer id;
     private int orderid;
     private String itemcode;
     private int quantityOrdered;
     private int quantitySupplied;
     private String status;

    public Orderitems() {
    }

    public Orderitems(int orderid, String itemcode, int quantityOrdered, int quantitySupplied, String status) {
       this.orderid = orderid;
       this.itemcode = itemcode;
       this.quantityOrdered = quantityOrdered;
       this.quantitySupplied = quantitySupplied;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }
    public String getItemcode() {
        return this.itemcode;
    }
    
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }
    public int getQuantityOrdered() {
        return this.quantityOrdered;
    }
    
    public void setQuantityOrdered(int quantityOrdered) {
        this.quantityOrdered = quantityOrdered;
    }
    public int getQuantitySupplied() {
        return this.quantitySupplied;
    }
    
    public void setQuantitySupplied(int quantitySupplied) {
        this.quantitySupplied = quantitySupplied;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


