package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatientTreatmentNotes generated by hbm2java
 */
@Entity
@Table(name="patient_treatment_notes"
    ,catalog="extended"
)
public class PatientTreatmentNotes  implements java.io.Serializable {


     private Integer id;
     private String treatmentNote;
     private String patientid;
     private int visitid;

    public PatientTreatmentNotes() {
    }

    public PatientTreatmentNotes(String treatmentNote, String patientid, int visitid) {
       this.treatmentNote = treatmentNote;
       this.patientid = patientid;
       this.visitid = visitid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="treatment_note", nullable=false, length=65535)
    public String getTreatmentNote() {
        return this.treatmentNote;
    }
    
    public void setTreatmentNote(String treatmentNote) {
        this.treatmentNote = treatmentNote;
    }
    
    @Column(name="patientid", nullable=false, length=10)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }




}


