package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatientBed generated by hbm2java
 */
@Entity
@Table(name="patient_bed"
    ,catalog="extended"
)
public class PatientBed  implements java.io.Serializable {


     private int visitid;
     private String patientid;
     private int bedid;

    public PatientBed() {
    }

    public PatientBed(int visitid, String patientid, int bedid) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.bedid = bedid;
    }
   
     @Id 
    
    @Column(name="visitid", unique=true, nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="patientid", nullable=false, length=100)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="bedid", nullable=false)
    public int getBedid() {
        return this.bedid;
    }
    
    public void setBedid(int bedid) {
        this.bedid = bedid;
    }




}


