package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatientCharacteristics generated by hbm2java
 */
@Entity
@Table(name="patient_characteristics"
    ,catalog="extended"
)
public class PatientCharacteristics  implements java.io.Serializable {


     private Integer id;
     private int characteristicId;
     private String patientid;
     private int visitid;

    public PatientCharacteristics() {
    }

    public PatientCharacteristics(int characteristicId, String patientid, int visitid) {
       this.characteristicId = characteristicId;
       this.patientid = patientid;
       this.visitid = visitid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="characteristic_id", nullable=false)
    public int getCharacteristicId() {
        return this.characteristicId;
    }
    
    public void setCharacteristicId(int characteristicId) {
        this.characteristicId = characteristicId;
    }
    
    @Column(name="patientid", nullable=false, length=10)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }




}


