package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatientAllergies generated by hbm2java
 */
@Entity
@Table(name="patient_allergies"
    ,catalog="extended"
)
public class PatientAllergies  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private int allergyid;

    public PatientAllergies() {
    }

    public PatientAllergies(String patientid, int allergyid) {
       this.patientid = patientid;
       this.allergyid = allergyid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="patientid", nullable=false, length=100)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="allergyid", nullable=false)
    public int getAllergyid() {
        return this.allergyid;
    }
    
    public void setAllergyid(int allergyid) {
        this.allergyid = allergyid;
    }




}


