package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patientdiagnosis generated by hbm2java
 */
@Entity
@Table(name="patientdiagnosis"
    ,catalog="extended"
)
public class Patientdiagnosis  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private int diagnosisid;
     private String code;
     private int visitationid;
     private Date date;

    public Patientdiagnosis() {
    }

    public Patientdiagnosis(String patientid, int diagnosisid, String code, int visitationid, Date date) {
       this.patientid = patientid;
       this.diagnosisid = diagnosisid;
       this.code = code;
       this.visitationid = visitationid;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="patientid", nullable=false, length=20)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="diagnosisid", nullable=false)
    public int getDiagnosisid() {
        return this.diagnosisid;
    }
    
    public void setDiagnosisid(int diagnosisid) {
        this.diagnosisid = diagnosisid;
    }
    
    @Column(name="code", nullable=false, length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="visitationid", nullable=false)
    public int getVisitationid() {
        return this.visitationid;
    }
    
    public void setVisitationid(int visitationid) {
        this.visitationid = visitationid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


