package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientTreatmentBatch generated by hbm2java
 */
@Entity
@Table(name="patient_treatment_batch"
    ,catalog="extended"
)
public class PatientTreatmentBatch  implements java.io.Serializable {


     private Integer objectId;
     private Patienttreatment patienttreatment;
     private DispensaryBatch dispensaryBatch;

    public PatientTreatmentBatch() {
    }

    public PatientTreatmentBatch(Patienttreatment patienttreatment, DispensaryBatch dispensaryBatch) {
       this.patienttreatment = patienttreatment;
       this.dispensaryBatch = dispensaryBatch;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="object_id", unique=true, nullable=false)
    public Integer getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_treatment_id", nullable=false)
    public Patienttreatment getPatienttreatment() {
        return this.patienttreatment;
    }
    
    public void setPatienttreatment(Patienttreatment patienttreatment) {
        this.patienttreatment = patienttreatment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="batch_number", nullable=false)
    public DispensaryBatch getDispensaryBatch() {
        return this.dispensaryBatch;
    }
    
    public void setDispensaryBatch(DispensaryBatch dispensaryBatch) {
        this.dispensaryBatch = dispensaryBatch;
    }




}


