package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientProcedure generated by hbm2java
 */
@Entity
@Table(name="patient_procedure"
    ,catalog="extended"
)
public class PatientProcedure  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private String procedureCode;
     private Date date;
     private int visitid;
     private double amountpaid;
     private boolean copaid;
     private boolean isPrivate;
     private double secondaryAmount;
     private double privateAmount;

    public PatientProcedure() {
    }

    public PatientProcedure(String patientid, String procedureCode, Date date, int visitid, double amountpaid, boolean copaid, boolean isPrivate, double secondaryAmount, double privateAmount) {
       this.patientid = patientid;
       this.procedureCode = procedureCode;
       this.date = date;
       this.visitid = visitid;
       this.amountpaid = amountpaid;
       this.copaid = copaid;
       this.isPrivate = isPrivate;
       this.secondaryAmount = secondaryAmount;
       this.privateAmount = privateAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="patientid", nullable=false, length=100)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="procedure_code", nullable=false, length=100)
    public String getProcedureCode() {
        return this.procedureCode;
    }
    
    public void setProcedureCode(String procedureCode) {
        this.procedureCode = procedureCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="amountpaid", nullable=false, precision=22, scale=0)
    public double getAmountpaid() {
        return this.amountpaid;
    }
    
    public void setAmountpaid(double amountpaid) {
        this.amountpaid = amountpaid;
    }
    
    @Column(name="copaid", nullable=false)
    public boolean isCopaid() {
        return this.copaid;
    }
    
    public void setCopaid(boolean copaid) {
        this.copaid = copaid;
    }
    
    @Column(name="is_private", nullable=false)
    public boolean isIsPrivate() {
        return this.isPrivate;
    }
    
    public void setIsPrivate(boolean isPrivate) {
        this.isPrivate = isPrivate;
    }
    
    @Column(name="secondary_amount", nullable=false, precision=22, scale=0)
    public double getSecondaryAmount() {
        return this.secondaryAmount;
    }
    
    public void setSecondaryAmount(double secondaryAmount) {
        this.secondaryAmount = secondaryAmount;
    }
    
    @Column(name="private_amount", nullable=false, precision=22, scale=0)
    public double getPrivateAmount() {
        return this.privateAmount;
    }
    
    public void setPrivateAmount(double privateAmount) {
        this.privateAmount = privateAmount;
    }




}


