package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientRegistration generated by hbm2java
 */
@Entity
@Table(name="patient_registration"
    ,catalog="extended"
)
public class PatientRegistration  implements java.io.Serializable {


     private Integer regId;
     private String patientId;
     private boolean paymentStatus;
     private double amountPaid;
     private Date datePaid;
     private int regFeeId;
     private boolean copaid;
     private double secondaryPayment;
     private boolean personallySupported;
     private double personalSupportAmount;

    public PatientRegistration() {
    }

	
    public PatientRegistration(String patientId, boolean paymentStatus, double amountPaid, int regFeeId, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
        this.patientId = patientId;
        this.paymentStatus = paymentStatus;
        this.amountPaid = amountPaid;
        this.regFeeId = regFeeId;
        this.copaid = copaid;
        this.secondaryPayment = secondaryPayment;
        this.personallySupported = personallySupported;
        this.personalSupportAmount = personalSupportAmount;
    }
    public PatientRegistration(String patientId, boolean paymentStatus, double amountPaid, Date datePaid, int regFeeId, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
       this.patientId = patientId;
       this.paymentStatus = paymentStatus;
       this.amountPaid = amountPaid;
       this.datePaid = datePaid;
       this.regFeeId = regFeeId;
       this.copaid = copaid;
       this.secondaryPayment = secondaryPayment;
       this.personallySupported = personallySupported;
       this.personalSupportAmount = personalSupportAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="reg_id", unique=true, nullable=false)
    public Integer getRegId() {
        return this.regId;
    }
    
    public void setRegId(Integer regId) {
        this.regId = regId;
    }
    
    @Column(name="patient_id", nullable=false, length=25)
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    
    @Column(name="payment_status", nullable=false)
    public boolean isPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(boolean paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    
    @Column(name="amount_paid", nullable=false, precision=22, scale=0)
    public double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(double amountPaid) {
        this.amountPaid = amountPaid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_paid", length=10)
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    
    @Column(name="reg_fee_id", nullable=false)
    public int getRegFeeId() {
        return this.regFeeId;
    }
    
    public void setRegFeeId(int regFeeId) {
        this.regFeeId = regFeeId;
    }
    
    @Column(name="copaid", nullable=false)
    public boolean isCopaid() {
        return this.copaid;
    }
    
    public void setCopaid(boolean copaid) {
        this.copaid = copaid;
    }
    
    @Column(name="secondary_payment", nullable=false, precision=22, scale=0)
    public double getSecondaryPayment() {
        return this.secondaryPayment;
    }
    
    public void setSecondaryPayment(double secondaryPayment) {
        this.secondaryPayment = secondaryPayment;
    }
    
    @Column(name="personally_supported", nullable=false)
    public boolean isPersonallySupported() {
        return this.personallySupported;
    }
    
    public void setPersonallySupported(boolean personallySupported) {
        this.personallySupported = personallySupported;
    }
    
    @Column(name="personal_support_amount", nullable=false, precision=22, scale=0)
    public double getPersonalSupportAmount() {
        return this.personalSupportAmount;
    }
    
    public void setPersonalSupportAmount(double personalSupportAmount) {
        this.personalSupportAmount = personalSupportAmount;
    }




}


