package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatientOnsets generated by hbm2java
 */
@Entity
@Table(name="patient_onsets"
    ,catalog="extended"
)
public class PatientOnsets  implements java.io.Serializable {


     private Integer id;
     private int onsetId;
     private String patientid;
     private int visitid;

    public PatientOnsets() {
    }

    public PatientOnsets(int onsetId, String patientid, int visitid) {
       this.onsetId = onsetId;
       this.patientid = patientid;
       this.visitid = visitid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="onset_id", nullable=false)
    public int getOnsetId() {
        return this.onsetId;
    }
    
    public void setOnsetId(int onsetId) {
        this.onsetId = onsetId;
    }
    
    @Column(name="patientid", nullable=false, length=10)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }




}


