package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Patientconsultation generated by hbm2java
 */
@Entity
@Table(name="patientconsultation"
    ,catalog="extended"
)
public class Patientconsultation  implements java.io.Serializable {


     private Integer id;
     private int visitid;
     private int typeid;
     private Double amountpaid;
     private String status;
     private boolean copaid;
     private double secondaryPayment;
     private boolean personallySupported;
     private double personalSupportAmount;

    public Patientconsultation() {
    }

	
    public Patientconsultation(int visitid, int typeid, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
        this.visitid = visitid;
        this.typeid = typeid;
        this.copaid = copaid;
        this.secondaryPayment = secondaryPayment;
        this.personallySupported = personallySupported;
        this.personalSupportAmount = personalSupportAmount;
    }
    public Patientconsultation(int visitid, int typeid, Double amountpaid, String status, boolean copaid, double secondaryPayment, boolean personallySupported, double personalSupportAmount) {
       this.visitid = visitid;
       this.typeid = typeid;
       this.amountpaid = amountpaid;
       this.status = status;
       this.copaid = copaid;
       this.secondaryPayment = secondaryPayment;
       this.personallySupported = personallySupported;
       this.personalSupportAmount = personalSupportAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="typeid", nullable=false)
    public int getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(int typeid) {
        this.typeid = typeid;
    }
    
    @Column(name="amountpaid", precision=22, scale=0)
    public Double getAmountpaid() {
        return this.amountpaid;
    }
    
    public void setAmountpaid(Double amountpaid) {
        this.amountpaid = amountpaid;
    }
    
    @Column(name="status", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="copaid", nullable=false)
    public boolean isCopaid() {
        return this.copaid;
    }
    
    public void setCopaid(boolean copaid) {
        this.copaid = copaid;
    }
    
    @Column(name="secondary_payment", nullable=false, precision=22, scale=0)
    public double getSecondaryPayment() {
        return this.secondaryPayment;
    }
    
    public void setSecondaryPayment(double secondaryPayment) {
        this.secondaryPayment = secondaryPayment;
    }
    
    @Column(name="personally_supported", nullable=false)
    public boolean isPersonallySupported() {
        return this.personallySupported;
    }
    
    public void setPersonallySupported(boolean personallySupported) {
        this.personallySupported = personallySupported;
    }
    
    @Column(name="personal_support_amount", nullable=false, precision=22, scale=0)
    public double getPersonalSupportAmount() {
        return this.personalSupportAmount;
    }
    
    public void setPersonalSupportAmount(double personalSupportAmount) {
        this.personalSupportAmount = personalSupportAmount;
    }




}


