package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatientMajorExaminations generated by hbm2java
 */
@Entity
@Table(name="patient_major_examinations"
    ,catalog="extended"
)
public class PatientMajorExaminations  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private int visitid;
     private String examinationNote;

    public PatientMajorExaminations() {
    }

    public PatientMajorExaminations(String patientid, int visitid, String examinationNote) {
       this.patientid = patientid;
       this.visitid = visitid;
       this.examinationNote = examinationNote;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="patientid", nullable=false, length=10)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="examination_note", nullable=false, length=65535)
    public String getExaminationNote() {
        return this.examinationNote;
    }
    
    public void setExaminationNote(String examinationNote) {
        this.examinationNote = examinationNote;
    }




}


