package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="permission"
    ,catalog="extended"
)
public class Permission  implements java.io.Serializable {


     private Integer permissionid;
     private String permission;
     private int departmentid;

    public Permission() {
    }

    public Permission(String permission, int departmentid) {
       this.permission = permission;
       this.departmentid = departmentid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="permissionid", unique=true, nullable=false)
    public Integer getPermissionid() {
        return this.permissionid;
    }
    
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
    
    @Column(name="permission", nullable=false, length=65535)
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }
    
    @Column(name="departmentid", nullable=false)
    public int getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(int departmentid) {
        this.departmentid = departmentid;
    }




}


