package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pharmorder generated by hbm2java
 */
@Entity
@Table(name="pharmorder"
    ,catalog="extended"
)
public class Pharmorder  implements java.io.Serializable {


     private String orderid;
     private String patientid;
     private String fromdoc;
     private Date orderdate;
     private Date dispenseddate;
     private Integer visitid;
     private String dispensed;
     private Double amoutpaid;
     private Double outstanding;
     private double totalAmount;
     private String dispensedBy;
     private String receivedBy;
     private Set<TransitionOrder> transitionOrders = new HashSet<TransitionOrder>(0);
     private Set<Patienttreatment> patienttreatments = new HashSet<Patienttreatment>(0);

    public Pharmorder() {
    }

	
    public Pharmorder(String orderid, String patientid, Date orderdate, double totalAmount, String dispensedBy, String receivedBy) {
        this.orderid = orderid;
        this.patientid = patientid;
        this.orderdate = orderdate;
        this.totalAmount = totalAmount;
        this.dispensedBy = dispensedBy;
        this.receivedBy = receivedBy;
    }
    public Pharmorder(String orderid, String patientid, String fromdoc, Date orderdate, Date dispenseddate, Integer visitid, String dispensed, Double amoutpaid, Double outstanding, double totalAmount, String dispensedBy, String receivedBy, Set<TransitionOrder> transitionOrders, Set<Patienttreatment> patienttreatments) {
       this.orderid = orderid;
       this.patientid = patientid;
       this.fromdoc = fromdoc;
       this.orderdate = orderdate;
       this.dispenseddate = dispenseddate;
       this.visitid = visitid;
       this.dispensed = dispensed;
       this.amoutpaid = amoutpaid;
       this.outstanding = outstanding;
       this.totalAmount = totalAmount;
       this.dispensedBy = dispensedBy;
       this.receivedBy = receivedBy;
       this.transitionOrders = transitionOrders;
       this.patienttreatments = patienttreatments;
    }
   
     @Id 
    
    @Column(name="orderid", unique=true, nullable=false, length=50)
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    
    @Column(name="patientid", nullable=false, length=65535)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="fromdoc", length=65535)
    public String getFromdoc() {
        return this.fromdoc;
    }
    
    public void setFromdoc(String fromdoc) {
        this.fromdoc = fromdoc;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="orderdate", nullable=false, length=10)
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dispenseddate", length=10)
    public Date getDispenseddate() {
        return this.dispenseddate;
    }
    
    public void setDispenseddate(Date dispenseddate) {
        this.dispenseddate = dispenseddate;
    }
    
    @Column(name="visitid")
    public Integer getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(Integer visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="dispensed", length=50)
    public String getDispensed() {
        return this.dispensed;
    }
    
    public void setDispensed(String dispensed) {
        this.dispensed = dispensed;
    }
    
    @Column(name="amoutpaid", precision=22, scale=0)
    public Double getAmoutpaid() {
        return this.amoutpaid;
    }
    
    public void setAmoutpaid(Double amoutpaid) {
        this.amoutpaid = amoutpaid;
    }
    
    @Column(name="outstanding", precision=22, scale=0)
    public Double getOutstanding() {
        return this.outstanding;
    }
    
    public void setOutstanding(Double outstanding) {
        this.outstanding = outstanding;
    }
    
    @Column(name="total_amount", nullable=false, precision=22, scale=0)
    public double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }
    
    @Column(name="dispensed_by", nullable=false)
    public String getDispensedBy() {
        return this.dispensedBy;
    }
    
    public void setDispensedBy(String dispensedBy) {
        this.dispensedBy = dispensedBy;
    }
    
    @Column(name="received_by", nullable=false)
    public String getReceivedBy() {
        return this.receivedBy;
    }
    
    public void setReceivedBy(String receivedBy) {
        this.receivedBy = receivedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pharmorder")
    public Set<TransitionOrder> getTransitionOrders() {
        return this.transitionOrders;
    }
    
    public void setTransitionOrders(Set<TransitionOrder> transitionOrders) {
        this.transitionOrders = transitionOrders;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pharmorder")
    public Set<Patienttreatment> getPatienttreatments() {
        return this.patienttreatments;
    }
    
    public void setPatienttreatments(Set<Patienttreatment> patienttreatments) {
        this.patienttreatments = patienttreatments;
    }




}


