package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PossibleinvResults generated by hbm2java
 */
@Entity
@Table(name="possibleinv_results"
    ,catalog="extended"
)
public class PossibleinvResults  implements java.io.Serializable {


     private Integer posinvResultId;
     private String posinvResult;

    public PossibleinvResults() {
    }

    public PossibleinvResults(String posinvResult) {
       this.posinvResult = posinvResult;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="posinv_result_id", unique=true, nullable=false)
    public Integer getPosinvResultId() {
        return this.posinvResultId;
    }
    
    public void setPosinvResultId(Integer posinvResultId) {
        this.posinvResultId = posinvResultId;
    }
    
    @Column(name="posinv_result", nullable=false)
    public String getPosinvResult() {
        return this.posinvResult;
    }
    
    public void setPosinvResult(String posinvResult) {
        this.posinvResult = posinvResult;
    }




}


