package entities;
// Generated Nov 25, 2013 10:35:09 AM by Hibernate Tools 3.2.1.GA



/**
 * PostedItems generated by hbm2java
 */
public class PostedItems  implements java.io.Serializable {


     private Integer postid;
     private int requestid;
     private String batchNumber;
     private int qunatity;

    public PostedItems() {
    }

    public PostedItems(int requestid, String batchNumber, int qunatity) {
       this.requestid = requestid;
       this.batchNumber = batchNumber;
       this.qunatity = qunatity;
    }
   
    public Integer getPostid() {
        return this.postid;
    }
    
    public void setPostid(Integer postid) {
        this.postid = postid;
    }
    public int getRequestid() {
        return this.requestid;
    }
    
    public void setRequestid(int requestid) {
        this.requestid = requestid;
    }
    public String getBatchNumber() {
        return this.batchNumber;
    }
    
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }
    public int getQunatity() {
        return this.qunatity;
    }
    
    public void setQunatity(int qunatity) {
        this.qunatity = qunatity;
    }




}


