package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProblemOptions generated by hbm2java
 */
@Entity
@Table(name="problem_options"
    ,catalog="extended"
)
public class ProblemOptions  implements java.io.Serializable {


     private Integer problemId;
     private String problemName;

    public ProblemOptions() {
    }

    public ProblemOptions(String problemName) {
       this.problemName = problemName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="problem_id", unique=true, nullable=false)
    public Integer getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }
    
    @Column(name="problem_name", nullable=false)
    public String getProblemName() {
        return this.problemName;
    }
    
    public void setProblemName(String problemName) {
        this.problemName = problemName;
    }




}


