package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Procedureorders generated by hbm2java
 */
@Entity
@Table(name="procedureorders"
    ,catalog="extended"
)
public class Procedureorders  implements java.io.Serializable {


     private Integer orderid;
     private int visitid;
     private String patientid;
     private double total;
     private double amoutpaid;
     private String status;
     private Date orderdate;
     private String orderedby;
     private String performedby;

    public Procedureorders() {
    }

    public Procedureorders(int visitid, String patientid, double total, double amoutpaid, String status, Date orderdate, String orderedby, String performedby) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.total = total;
       this.amoutpaid = amoutpaid;
       this.status = status;
       this.orderdate = orderdate;
       this.orderedby = orderedby;
       this.performedby = performedby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="orderid", unique=true, nullable=false)
    public Integer getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="patientid", nullable=false, length=100)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="total", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    
    @Column(name="amoutpaid", nullable=false, precision=22, scale=0)
    public double getAmoutpaid() {
        return this.amoutpaid;
    }
    
    public void setAmoutpaid(double amoutpaid) {
        this.amoutpaid = amoutpaid;
    }
    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orderdate", nullable=false, length=19)
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    
    @Column(name="orderedby", nullable=false)
    public String getOrderedby() {
        return this.orderedby;
    }
    
    public void setOrderedby(String orderedby) {
        this.orderedby = orderedby;
    }
    
    @Column(name="performedby", nullable=false)
    public String getPerformedby() {
        return this.performedby;
    }
    
    public void setPerformedby(String performedby) {
        this.performedby = performedby;
    }




}


