package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Procedureorderswalkin generated by hbm2java
 */
@Entity
@Table(name="procedureorderswalkin"
    ,catalog="extended"
)
public class Procedureorderswalkin  implements java.io.Serializable {


     private String orderid;
     private String firstName;
     private String lastName;
     private String gender;
     private Date dateOfBirth;
     private double total;
     private double amoutpaid;
     private String status;
     private Date orderdate;
     private String orderedby;
     private String performedby;

    public Procedureorderswalkin() {
    }

	
    public Procedureorderswalkin(String orderid, String firstName, String lastName, String gender, double total, double amoutpaid, String status, Date orderdate, String orderedby, String performedby) {
        this.orderid = orderid;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.total = total;
        this.amoutpaid = amoutpaid;
        this.status = status;
        this.orderdate = orderdate;
        this.orderedby = orderedby;
        this.performedby = performedby;
    }
    public Procedureorderswalkin(String orderid, String firstName, String lastName, String gender, Date dateOfBirth, double total, double amoutpaid, String status, Date orderdate, String orderedby, String performedby) {
       this.orderid = orderid;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.total = total;
       this.amoutpaid = amoutpaid;
       this.status = status;
       this.orderdate = orderdate;
       this.orderedby = orderedby;
       this.performedby = performedby;
    }
   
     @Id 
    
    @Column(name="orderid", unique=true, nullable=false)
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    
    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="last_name", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="gender", nullable=false)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_birth", length=19)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    
    @Column(name="total", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    
    @Column(name="amoutpaid", nullable=false, precision=22, scale=0)
    public double getAmoutpaid() {
        return this.amoutpaid;
    }
    
    public void setAmoutpaid(double amoutpaid) {
        this.amoutpaid = amoutpaid;
    }
    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orderdate", nullable=false, length=19)
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    
    @Column(name="orderedby", nullable=false)
    public String getOrderedby() {
        return this.orderedby;
    }
    
    public void setOrderedby(String orderedby) {
        this.orderedby = orderedby;
    }
    
    @Column(name="performedby", nullable=false)
    public String getPerformedby() {
        return this.performedby;
    }
    
    public void setPerformedby(String performedby) {
        this.performedby = performedby;
    }




}


