package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name="profile"
    ,catalog="extended"
)
public class Profile  implements java.io.Serializable {


     private Integer profileId;
     private String profileDescription;
     private double profileAmount;

    public Profile() {
    }

    public Profile(String profileDescription, double profileAmount) {
       this.profileDescription = profileDescription;
       this.profileAmount = profileAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="profile_id", unique=true, nullable=false)
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    
    @Column(name="profile_description", nullable=false, length=65535)
    public String getProfileDescription() {
        return this.profileDescription;
    }
    
    public void setProfileDescription(String profileDescription) {
        this.profileDescription = profileDescription;
    }
    
    @Column(name="profile_amount", nullable=false, precision=22, scale=0)
    public double getProfileAmount() {
        return this.profileAmount;
    }
    
    public void setProfileAmount(double profileAmount) {
        this.profileAmount = profileAmount;
    }




}


