package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfileDetails generated by hbm2java
 */
@Entity
@Table(name="profile_details"
    ,catalog="extended"
)
public class ProfileDetails  implements java.io.Serializable {


     private Integer detailId;
     private int profileId;
     private int labId;

    public ProfileDetails() {
    }

    public ProfileDetails(int profileId, int labId) {
       this.profileId = profileId;
       this.labId = labId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="detail_id", unique=true, nullable=false)
    public Integer getDetailId() {
        return this.detailId;
    }
    
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }
    
    @Column(name="profile_id", nullable=false)
    public int getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(int profileId) {
        this.profileId = profileId;
    }
    
    @Column(name="lab_id", nullable=false)
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }




}


