package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PurchaseOrderItems generated by hbm2java
 */
@Entity
@Table(name="purchase_order_items"
    ,catalog="extended"
)
public class PurchaseOrderItems  implements java.io.Serializable {


     private Integer orderItemsId;
     private PurchaseOrder purchaseOrder;
     private InventoryItems inventoryItems;
     private int quantityOrdered;
     private int quantityDelivered;

    public PurchaseOrderItems() {
    }

    public PurchaseOrderItems(PurchaseOrder purchaseOrder, InventoryItems inventoryItems, int quantityOrdered, int quantityDelivered) {
       this.purchaseOrder = purchaseOrder;
       this.inventoryItems = inventoryItems;
       this.quantityOrdered = quantityOrdered;
       this.quantityDelivered = quantityDelivered;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="order_items_id", unique=true, nullable=false)
    public Integer getOrderItemsId() {
        return this.orderItemsId;
    }
    
    public void setOrderItemsId(Integer orderItemsId) {
        this.orderItemsId = orderItemsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orderid", nullable=false)
    public PurchaseOrder getPurchaseOrder() {
        return this.purchaseOrder;
    }
    
    public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
        this.purchaseOrder = purchaseOrder;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_code", nullable=false)
    public InventoryItems getInventoryItems() {
        return this.inventoryItems;
    }
    
    public void setInventoryItems(InventoryItems inventoryItems) {
        this.inventoryItems = inventoryItems;
    }
    
    @Column(name="quantity_ordered", nullable=false)
    public int getQuantityOrdered() {
        return this.quantityOrdered;
    }
    
    public void setQuantityOrdered(int quantityOrdered) {
        this.quantityOrdered = quantityOrdered;
    }
    
    @Column(name="quantity_delivered", nullable=false)
    public int getQuantityDelivered() {
        return this.quantityDelivered;
    }
    
    public void setQuantityDelivered(int quantityDelivered) {
        this.quantityDelivered = quantityDelivered;
    }




}


