package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReferringDoctors generated by hbm2java
 */
@Entity
@Table(name="referring_doctors"
    ,catalog="extended"
)
public class ReferringDoctors  implements java.io.Serializable {


     private Integer id;
     private String nameName;
     private String facility;

    public ReferringDoctors() {
    }

    public ReferringDoctors(String nameName, String facility) {
       this.nameName = nameName;
       this.facility = facility;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name_name", nullable=false, length=65535)
    public String getNameName() {
        return this.nameName;
    }
    
    public void setNameName(String nameName) {
        this.nameName = nameName;
    }
    
    @Column(name="facility", nullable=false, length=65535)
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }




}


