package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requisition generated by hbm2java
 */
@Entity
@Table(name="requisition"
    ,catalog="extended"
)
public class Requisition  implements java.io.Serializable {


     private Integer requestId;
     private Stafftable stafftableByRequestApprovedBy;
     private Stafftable stafftableByRequestedBy;
     private Stafftable stafftableByDeliveredBy;
     private Stafftable stafftableByDeliveryApprovedBy;
     private InventoryItems inventoryItems;
     private int quantityRequested;
     private Date dateOfRequest;
     private Date dateDelivered;
     private Integer quantityDelivered;
     private String status;
     private String location;

    public Requisition() {
    }

	
    public Requisition(Stafftable stafftableByRequestedBy, InventoryItems inventoryItems, int quantityRequested, Date dateOfRequest, String status, String location) {
        this.stafftableByRequestedBy = stafftableByRequestedBy;
        this.inventoryItems = inventoryItems;
        this.quantityRequested = quantityRequested;
        this.dateOfRequest = dateOfRequest;
        this.status = status;
        this.location = location;
    }
    public Requisition(Stafftable stafftableByRequestApprovedBy, Stafftable stafftableByRequestedBy, Stafftable stafftableByDeliveredBy, Stafftable stafftableByDeliveryApprovedBy, InventoryItems inventoryItems, int quantityRequested, Date dateOfRequest, Date dateDelivered, Integer quantityDelivered, String status, String location) {
       this.stafftableByRequestApprovedBy = stafftableByRequestApprovedBy;
       this.stafftableByRequestedBy = stafftableByRequestedBy;
       this.stafftableByDeliveredBy = stafftableByDeliveredBy;
       this.stafftableByDeliveryApprovedBy = stafftableByDeliveryApprovedBy;
       this.inventoryItems = inventoryItems;
       this.quantityRequested = quantityRequested;
       this.dateOfRequest = dateOfRequest;
       this.dateDelivered = dateDelivered;
       this.quantityDelivered = quantityDelivered;
       this.status = status;
       this.location = location;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="request_id", unique=true, nullable=false)
    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="request_approved_by")
    public Stafftable getStafftableByRequestApprovedBy() {
        return this.stafftableByRequestApprovedBy;
    }
    
    public void setStafftableByRequestApprovedBy(Stafftable stafftableByRequestApprovedBy) {
        this.stafftableByRequestApprovedBy = stafftableByRequestApprovedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="requested_by", nullable=false)
    public Stafftable getStafftableByRequestedBy() {
        return this.stafftableByRequestedBy;
    }
    
    public void setStafftableByRequestedBy(Stafftable stafftableByRequestedBy) {
        this.stafftableByRequestedBy = stafftableByRequestedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="delivered_by")
    public Stafftable getStafftableByDeliveredBy() {
        return this.stafftableByDeliveredBy;
    }
    
    public void setStafftableByDeliveredBy(Stafftable stafftableByDeliveredBy) {
        this.stafftableByDeliveredBy = stafftableByDeliveredBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="delivery_approved_by")
    public Stafftable getStafftableByDeliveryApprovedBy() {
        return this.stafftableByDeliveryApprovedBy;
    }
    
    public void setStafftableByDeliveryApprovedBy(Stafftable stafftableByDeliveryApprovedBy) {
        this.stafftableByDeliveryApprovedBy = stafftableByDeliveryApprovedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_code", nullable=false)
    public InventoryItems getInventoryItems() {
        return this.inventoryItems;
    }
    
    public void setInventoryItems(InventoryItems inventoryItems) {
        this.inventoryItems = inventoryItems;
    }
    
    @Column(name="quantity_requested", nullable=false)
    public int getQuantityRequested() {
        return this.quantityRequested;
    }
    
    public void setQuantityRequested(int quantityRequested) {
        this.quantityRequested = quantityRequested;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_of_request", nullable=false, length=10)
    public Date getDateOfRequest() {
        return this.dateOfRequest;
    }
    
    public void setDateOfRequest(Date dateOfRequest) {
        this.dateOfRequest = dateOfRequest;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_delivered", length=10)
    public Date getDateDelivered() {
        return this.dateDelivered;
    }
    
    public void setDateDelivered(Date dateDelivered) {
        this.dateDelivered = dateDelivered;
    }
    
    @Column(name="quantity_delivered")
    public Integer getQuantityDelivered() {
        return this.quantityDelivered;
    }
    
    public void setQuantityDelivered(Integer quantityDelivered) {
        this.quantityDelivered = quantityDelivered;
    }
    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="location", nullable=false, length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


