package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roletable generated by hbm2java
 */
@Entity
@Table(name="roletable"
    ,catalog="extended"
)
public class Roletable  implements java.io.Serializable {


     private Integer roleid;
     private String rolename;
     private String roledescription;

    public Roletable() {
    }

    public Roletable(String rolename, String roledescription) {
       this.rolename = rolename;
       this.roledescription = roledescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="roleid", unique=true, nullable=false)
    public Integer getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
    
    @Column(name="rolename", nullable=false, length=50)
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    
    @Column(name="roledescription", nullable=false)
    public String getRoledescription() {
        return this.roledescription;
    }
    
    public void setRoledescription(String roledescription) {
        this.roledescription = roledescription;
    }




}


