package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="room"
    ,catalog="extended"
)
public class Room  implements java.io.Serializable {


     private Integer roomid;
     private String description;
     private int numberOfBeds;
     private int status;
     private double cost;
     private int wardId;

    public Room() {
    }

    public Room(String description, int numberOfBeds, int status, double cost, int wardId) {
       this.description = description;
       this.numberOfBeds = numberOfBeds;
       this.status = status;
       this.cost = cost;
       this.wardId = wardId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="roomid", unique=true, nullable=false)
    public Integer getRoomid() {
        return this.roomid;
    }
    
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }
    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="number_of_beds", nullable=false)
    public int getNumberOfBeds() {
        return this.numberOfBeds;
    }
    
    public void setNumberOfBeds(int numberOfBeds) {
        this.numberOfBeds = numberOfBeds;
    }
    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    
    @Column(name="cost", nullable=false, precision=22, scale=0)
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }
    
    @Column(name="ward_id", nullable=false)
    public int getWardId() {
        return this.wardId;
    }
    
    public void setWardId(int wardId) {
        this.wardId = wardId;
    }




}


