package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SocialHistories generated by hbm2java
 */
@Entity
@Table(name="social_histories"
    ,catalog="extended"
)
public class SocialHistories  implements java.io.Serializable {


     private Integer socialHistoryId;
     private String socialHistory;

    public SocialHistories() {
    }

    public SocialHistories(String socialHistory) {
       this.socialHistory = socialHistory;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="social_history_id", unique=true, nullable=false)
    public Integer getSocialHistoryId() {
        return this.socialHistoryId;
    }
    
    public void setSocialHistoryId(Integer socialHistoryId) {
        this.socialHistoryId = socialHistoryId;
    }
    
    @Column(name="social_history", nullable=false)
    public String getSocialHistory() {
        return this.socialHistory;
    }
    
    public void setSocialHistory(String socialHistory) {
        this.socialHistory = socialHistory;
    }




}


