package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sponsorship generated by hbm2java
 */
@Entity
@Table(name="sponsorship"
    ,catalog="extended"
)
public class Sponsorship  implements java.io.Serializable {


     private String sponshorshipid;
     private String sponsorname;
     private String type;
     private String address;
     private String contact;
     private String email;
     private Double labmarkup;
     private Double treatmentMarkup;
     private double markupTreatPercentage;
     private double markupLabPercentage;

    public Sponsorship() {
    }

	
    public Sponsorship(String sponshorshipid, double markupTreatPercentage, double markupLabPercentage) {
        this.sponshorshipid = sponshorshipid;
        this.markupTreatPercentage = markupTreatPercentage;
        this.markupLabPercentage = markupLabPercentage;
    }
    public Sponsorship(String sponshorshipid, String sponsorname, String type, String address, String contact, String email, Double labmarkup, Double treatmentMarkup, double markupTreatPercentage, double markupLabPercentage) {
       this.sponshorshipid = sponshorshipid;
       this.sponsorname = sponsorname;
       this.type = type;
       this.address = address;
       this.contact = contact;
       this.email = email;
       this.labmarkup = labmarkup;
       this.treatmentMarkup = treatmentMarkup;
       this.markupTreatPercentage = markupTreatPercentage;
       this.markupLabPercentage = markupLabPercentage;
    }
   
     @Id 
    
    @Column(name="sponshorshipid", unique=true, nullable=false, length=50)
    public String getSponshorshipid() {
        return this.sponshorshipid;
    }
    
    public void setSponshorshipid(String sponshorshipid) {
        this.sponshorshipid = sponshorshipid;
    }
    
    @Column(name="sponsorname", length=150)
    public String getSponsorname() {
        return this.sponsorname;
    }
    
    public void setSponsorname(String sponsorname) {
        this.sponsorname = sponsorname;
    }
    
    @Column(name="type", length=150)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="address", length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="contact", length=10)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="labmarkup", precision=22, scale=0)
    public Double getLabmarkup() {
        return this.labmarkup;
    }
    
    public void setLabmarkup(Double labmarkup) {
        this.labmarkup = labmarkup;
    }
    
    @Column(name="treatment_markup", precision=22, scale=0)
    public Double getTreatmentMarkup() {
        return this.treatmentMarkup;
    }
    
    public void setTreatmentMarkup(Double treatmentMarkup) {
        this.treatmentMarkup = treatmentMarkup;
    }
    
    @Column(name="markup_treat_percentage", nullable=false, precision=22, scale=0)
    public double getMarkupTreatPercentage() {
        return this.markupTreatPercentage;
    }
    
    public void setMarkupTreatPercentage(double markupTreatPercentage) {
        this.markupTreatPercentage = markupTreatPercentage;
    }
    
    @Column(name="markup_lab_percentage", nullable=false, precision=22, scale=0)
    public double getMarkupLabPercentage() {
        return this.markupLabPercentage;
    }
    
    public void setMarkupLabPercentage(double markupLabPercentage) {
        this.markupLabPercentage = markupLabPercentage;
    }




}


