package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sponsorhipdetails generated by hbm2java
 */
@Entity
@Table(name="sponsorhipdetails"
    ,catalog="extended"
)
public class Sponsorhipdetails  implements java.io.Serializable {


     private String patientid;
     private String membershipid;
     private String type;
     private String benefitplan;
     private String sponsorid;
     private String dependentnumber;
     private String secondarySponsor;
     private String secondaryType;
     private String secondaryBenefitplan;
     private String secondaryMembership;

    public Sponsorhipdetails() {
    }

	
    public Sponsorhipdetails(String patientid) {
        this.patientid = patientid;
    }
    public Sponsorhipdetails(String patientid, String membershipid, String type, String benefitplan, String sponsorid, String dependentnumber, String secondarySponsor, String secondaryType, String secondaryBenefitplan, String secondaryMembership) {
       this.patientid = patientid;
       this.membershipid = membershipid;
       this.type = type;
       this.benefitplan = benefitplan;
       this.sponsorid = sponsorid;
       this.dependentnumber = dependentnumber;
       this.secondarySponsor = secondarySponsor;
       this.secondaryType = secondaryType;
       this.secondaryBenefitplan = secondaryBenefitplan;
       this.secondaryMembership = secondaryMembership;
    }
   
     @Id 
    
    @Column(name="patientid", unique=true, nullable=false, length=10)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="membershipid", length=50)
    public String getMembershipid() {
        return this.membershipid;
    }
    
    public void setMembershipid(String membershipid) {
        this.membershipid = membershipid;
    }
    
    @Column(name="type", length=250)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="benefitplan", length=200)
    public String getBenefitplan() {
        return this.benefitplan;
    }
    
    public void setBenefitplan(String benefitplan) {
        this.benefitplan = benefitplan;
    }
    
    @Column(name="sponsorid", length=50)
    public String getSponsorid() {
        return this.sponsorid;
    }
    
    public void setSponsorid(String sponsorid) {
        this.sponsorid = sponsorid;
    }
    
    @Column(name="dependentnumber", length=65535)
    public String getDependentnumber() {
        return this.dependentnumber;
    }
    
    public void setDependentnumber(String dependentnumber) {
        this.dependentnumber = dependentnumber;
    }
    
    @Column(name="secondary_sponsor", length=50)
    public String getSecondarySponsor() {
        return this.secondarySponsor;
    }
    
    public void setSecondarySponsor(String secondarySponsor) {
        this.secondarySponsor = secondarySponsor;
    }
    
    @Column(name="secondary_type", length=65535)
    public String getSecondaryType() {
        return this.secondaryType;
    }
    
    public void setSecondaryType(String secondaryType) {
        this.secondaryType = secondaryType;
    }
    
    @Column(name="secondary_benefitplan", length=65535)
    public String getSecondaryBenefitplan() {
        return this.secondaryBenefitplan;
    }
    
    public void setSecondaryBenefitplan(String secondaryBenefitplan) {
        this.secondaryBenefitplan = secondaryBenefitplan;
    }
    
    @Column(name="secondary_membership", length=65535)
    public String getSecondaryMembership() {
        return this.secondaryMembership;
    }
    
    public void setSecondaryMembership(String secondaryMembership) {
        this.secondaryMembership = secondaryMembership;
    }




}


