package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SponsorLabitemPrice generated by hbm2java
 */
@Entity
@Table(name="sponsor_labitem_price"
    ,catalog="extended"
)
public class SponsorLabitemPrice  implements java.io.Serializable {


     private Integer id;
     private String sponsorId;
     private double price;
     private int labItemId;

    public SponsorLabitemPrice() {
    }

    public SponsorLabitemPrice(String sponsorId, double price, int labItemId) {
       this.sponsorId = sponsorId;
       this.price = price;
       this.labItemId = labItemId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="sponsor_id", nullable=false)
    public String getSponsorId() {
        return this.sponsorId;
    }
    
    public void setSponsorId(String sponsorId) {
        this.sponsorId = sponsorId;
    }
    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    
    @Column(name="lab_item_id", nullable=false)
    public int getLabItemId() {
        return this.labItemId;
    }
    
    public void setLabItemId(int labItemId) {
        this.labItemId = labItemId;
    }




}


