package entities;
// Generated Aug 1, 2013 1:42:51 AM by Hibernate Tools 3.2.1.GA



/**
 * StaffPermission generated by hbm2java
 */
public class StaffPermission  implements java.io.Serializable {


     private Integer id;
     private String staffid;
     private int permissionid;

    public StaffPermission() {
    }

    public StaffPermission(String staffid, int permissionid) {
       this.staffid = staffid;
       this.permissionid = permissionid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }
    public int getPermissionid() {
        return this.permissionid;
    }
    
    public void setPermissionid(int permissionid) {
        this.permissionid = permissionid;
    }




}


