package entities;
// Generated Nov 15, 2013 8:19:17 PM by Hibernate Tools 3.2.1.GA



/**
 * StockItems generated by hbm2java
 */
public class StockItems  implements java.io.Serializable {


     private String code;
     private String icd10;
     private String description;
     private int typeId;
     private double markUp;
     private String unitOfPricing;
     private int qunaity;
     private int reOrderLevel;
     private int emergencyLevel;
     private String groupId;
     private int theragroup;

    public StockItems() {
    }

    public StockItems(String code, String icd10, String description, int typeId, double markUp, String unitOfPricing, int qunaity, int reOrderLevel, int emergencyLevel, String groupId, int theragroup) {
       this.code = code;
       this.icd10 = icd10;
       this.description = description;
       this.typeId = typeId;
       this.markUp = markUp;
       this.unitOfPricing = unitOfPricing;
       this.qunaity = qunaity;
       this.reOrderLevel = reOrderLevel;
       this.emergencyLevel = emergencyLevel;
       this.groupId = groupId;
       this.theragroup = theragroup;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getIcd10() {
        return this.icd10;
    }
    
    public void setIcd10(String icd10) {
        this.icd10 = icd10;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }
    public double getMarkUp() {
        return this.markUp;
    }
    
    public void setMarkUp(double markUp) {
        this.markUp = markUp;
    }
    public String getUnitOfPricing() {
        return this.unitOfPricing;
    }
    
    public void setUnitOfPricing(String unitOfPricing) {
        this.unitOfPricing = unitOfPricing;
    }
    public int getQunaity() {
        return this.qunaity;
    }
    
    public void setQunaity(int qunaity) {
        this.qunaity = qunaity;
    }
    public int getReOrderLevel() {
        return this.reOrderLevel;
    }
    
    public void setReOrderLevel(int reOrderLevel) {
        this.reOrderLevel = reOrderLevel;
    }
    public int getEmergencyLevel() {
        return this.emergencyLevel;
    }
    
    public void setEmergencyLevel(int emergencyLevel) {
        this.emergencyLevel = emergencyLevel;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public int getTheragroup() {
        return this.theragroup;
    }
    
    public void setTheragroup(int theragroup) {
        this.theragroup = theragroup;
    }




}


