package entities;
// Generated Nov 15, 2013 8:19:17 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StockOrders generated by hbm2java
 */
public class StockOrders  implements java.io.Serializable {


     private Integer orderid;
     private Date orderdate;
     private int supplier;
     private Date deliverydate;
     private String deliverer;
     private String orderer;
     private double cost;
     private String status;

    public StockOrders() {
    }

	
    public StockOrders(Date orderdate, int supplier, String orderer, double cost, String status) {
        this.orderdate = orderdate;
        this.supplier = supplier;
        this.orderer = orderer;
        this.cost = cost;
        this.status = status;
    }
    public StockOrders(Date orderdate, int supplier, Date deliverydate, String deliverer, String orderer, double cost, String status) {
       this.orderdate = orderdate;
       this.supplier = supplier;
       this.deliverydate = deliverydate;
       this.deliverer = deliverer;
       this.orderer = orderer;
       this.cost = cost;
       this.status = status;
    }
   
    public Integer getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    public int getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(int supplier) {
        this.supplier = supplier;
    }
    public Date getDeliverydate() {
        return this.deliverydate;
    }
    
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }
    public String getDeliverer() {
        return this.deliverer;
    }
    
    public void setDeliverer(String deliverer) {
        this.deliverer = deliverer;
    }
    public String getOrderer() {
        return this.orderer;
    }
    
    public void setOrderer(String orderer) {
        this.orderer = orderer;
    }
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


