package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="supplier"
    ,catalog="extended"
)
public class Supplier  implements java.io.Serializable {


     private Integer supplierid;
     private String name;
     private String address;
     private String telephone;
     private String email;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Supplier() {
    }

	
    public Supplier(String name, String address) {
        this.name = name;
        this.address = address;
    }
    public Supplier(String name, String address, String telephone, String email, Set<Invoice> invoices) {
       this.name = name;
       this.address = address;
       this.telephone = telephone;
       this.email = email;
       this.invoices = invoices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="supplierid", unique=true, nullable=false)
    public Integer getSupplierid() {
        return this.supplierid;
    }
    
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }
    
    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="address", nullable=false, length=65535)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="telephone", length=65535)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    @Column(name="email", length=65535)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


