package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TherapeuticGroup generated by hbm2java
 */
@Entity
@Table(name="therapeutic_group"
    ,catalog="extended"
)
public class TherapeuticGroup  implements java.io.Serializable {


     private Integer theraid;
     private String description;
     private Set<DispensaryItems> dispensaryItemses = new HashSet<DispensaryItems>(0);
     private Set<PharmacyItem> pharmacyItems = new HashSet<PharmacyItem>(0);
     private Set<InventoryItems> inventoryItemses = new HashSet<InventoryItems>(0);
     private Set<LaboratoryItem> laboratoryItems = new HashSet<LaboratoryItem>(0);

    public TherapeuticGroup() {
    }

	
    public TherapeuticGroup(String description) {
        this.description = description;
    }
    public TherapeuticGroup(String description, Set<DispensaryItems> dispensaryItemses, Set<PharmacyItem> pharmacyItems, Set<InventoryItems> inventoryItemses, Set<LaboratoryItem> laboratoryItems) {
       this.description = description;
       this.dispensaryItemses = dispensaryItemses;
       this.pharmacyItems = pharmacyItems;
       this.inventoryItemses = inventoryItemses;
       this.laboratoryItems = laboratoryItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="theraid", unique=true, nullable=false)
    public Integer getTheraid() {
        return this.theraid;
    }
    
    public void setTheraid(Integer theraid) {
        this.theraid = theraid;
    }
    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="therapeuticGroup")
    public Set<DispensaryItems> getDispensaryItemses() {
        return this.dispensaryItemses;
    }
    
    public void setDispensaryItemses(Set<DispensaryItems> dispensaryItemses) {
        this.dispensaryItemses = dispensaryItemses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="therapeuticGroup")
    public Set<PharmacyItem> getPharmacyItems() {
        return this.pharmacyItems;
    }
    
    public void setPharmacyItems(Set<PharmacyItem> pharmacyItems) {
        this.pharmacyItems = pharmacyItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="therapeuticGroup")
    public Set<InventoryItems> getInventoryItemses() {
        return this.inventoryItemses;
    }
    
    public void setInventoryItemses(Set<InventoryItems> inventoryItemses) {
        this.inventoryItemses = inventoryItemses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="therapeuticGroup")
    public Set<LaboratoryItem> getLaboratoryItems() {
        return this.laboratoryItems;
    }
    
    public void setLaboratoryItems(Set<LaboratoryItem> laboratoryItems) {
        this.laboratoryItems = laboratoryItems;
    }




}


