package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transferlocation generated by hbm2java
 */
@Entity
@Table(name="transferlocation"
    ,catalog="extended"
)
public class Transferlocation  implements java.io.Serializable {


     private Integer transferid;
     private int visitid;
     private Date visitdate;
     private String location;
     private String doctorid;
     private int diagnosisid;
     private String note;

    public Transferlocation() {
    }

	
    public Transferlocation(int visitid, Date visitdate, String location, String doctorid, int diagnosisid) {
        this.visitid = visitid;
        this.visitdate = visitdate;
        this.location = location;
        this.doctorid = doctorid;
        this.diagnosisid = diagnosisid;
    }
    public Transferlocation(int visitid, Date visitdate, String location, String doctorid, int diagnosisid, String note) {
       this.visitid = visitid;
       this.visitdate = visitdate;
       this.location = location;
       this.doctorid = doctorid;
       this.diagnosisid = diagnosisid;
       this.note = note;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="transferid", unique=true, nullable=false)
    public Integer getTransferid() {
        return this.transferid;
    }
    
    public void setTransferid(Integer transferid) {
        this.transferid = transferid;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="visitdate", nullable=false, length=10)
    public Date getVisitdate() {
        return this.visitdate;
    }
    
    public void setVisitdate(Date visitdate) {
        this.visitdate = visitdate;
    }
    
    @Column(name="location", nullable=false)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    @Column(name="doctorid", nullable=false)
    public String getDoctorid() {
        return this.doctorid;
    }
    
    public void setDoctorid(String doctorid) {
        this.doctorid = doctorid;
    }
    
    @Column(name="diagnosisid", nullable=false)
    public int getDiagnosisid() {
        return this.diagnosisid;
    }
    
    public void setDiagnosisid(int diagnosisid) {
        this.diagnosisid = diagnosisid;
    }
    
    @Column(name="note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


