package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransitionOrder generated by hbm2java
 */
@Entity
@Table(name="transition_order"
    ,catalog="extended"
)
public class TransitionOrder  implements java.io.Serializable {


     private Integer transitionId;
     private Pharmorder pharmorder;
     private String status;
     private String patientId;
     private Date dateOfOrder;
     private Set<Patienttreatment> patienttreatments = new HashSet<Patienttreatment>(0);

    public TransitionOrder() {
    }

	
    public TransitionOrder(Pharmorder pharmorder, String status, String patientId, Date dateOfOrder) {
        this.pharmorder = pharmorder;
        this.status = status;
        this.patientId = patientId;
        this.dateOfOrder = dateOfOrder;
    }
    public TransitionOrder(Pharmorder pharmorder, String status, String patientId, Date dateOfOrder, Set<Patienttreatment> patienttreatments) {
       this.pharmorder = pharmorder;
       this.status = status;
       this.patientId = patientId;
       this.dateOfOrder = dateOfOrder;
       this.patienttreatments = patienttreatments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="transition_id", unique=true, nullable=false)
    public Integer getTransitionId() {
        return this.transitionId;
    }
    
    public void setTransitionId(Integer transitionId) {
        this.transitionId = transitionId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pharmacy_id", nullable=false)
    public Pharmorder getPharmorder() {
        return this.pharmorder;
    }
    
    public void setPharmorder(Pharmorder pharmorder) {
        this.pharmorder = pharmorder;
    }
    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="patient_id", nullable=false)
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_of_order", nullable=false, length=10)
    public Date getDateOfOrder() {
        return this.dateOfOrder;
    }
    
    public void setDateOfOrder(Date dateOfOrder) {
        this.dateOfOrder = dateOfOrder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="transitionOrder")
    public Set<Patienttreatment> getPatienttreatments() {
        return this.patienttreatments;
    }
    
    public void setPatienttreatments(Set<Patienttreatment> patienttreatments) {
        this.patienttreatments = patienttreatments;
    }




}


