package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransitClinicLabs generated by hbm2java
 */
@Entity
@Table(name="transit_clinic_labs"
    ,catalog="extended"
)
public class TransitClinicLabs  implements java.io.Serializable {


     private String orderid;
     private String patientid;
     private String fromdoc;
     private Date orderdate;
     private int visitid;
     private String done;

    public TransitClinicLabs() {
    }

    public TransitClinicLabs(String orderid, String patientid, String fromdoc, Date orderdate, int visitid, String done) {
       this.orderid = orderid;
       this.patientid = patientid;
       this.fromdoc = fromdoc;
       this.orderdate = orderdate;
       this.visitid = visitid;
       this.done = done;
    }
   
     @Id 
    
    @Column(name="orderid", unique=true, nullable=false, length=100)
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    
    @Column(name="patientid", nullable=false, length=50)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="fromdoc", nullable=false)
    public String getFromdoc() {
        return this.fromdoc;
    }
    
    public void setFromdoc(String fromdoc) {
        this.fromdoc = fromdoc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orderdate", nullable=false, length=19)
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="done", nullable=false, length=20)
    public String getDone() {
        return this.done;
    }
    
    public void setDone(String done) {
        this.done = done;
    }




}


