package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TreatmentOptions generated by hbm2java
 */
@Entity
@Table(name="treatment_options"
    ,catalog="extended"
)
public class TreatmentOptions  implements java.io.Serializable {


     private Integer treatmentId;
     private String treatment;

    public TreatmentOptions() {
    }

    public TreatmentOptions(String treatment) {
       this.treatment = treatment;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="treatment_id", unique=true, nullable=false)
    public Integer getTreatmentId() {
        return this.treatmentId;
    }
    
    public void setTreatmentId(Integer treatmentId) {
        this.treatmentId = treatmentId;
    }
    
    @Column(name="treatment", nullable=false)
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }




}


