package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnitsOfMeasure generated by hbm2java
 */
@Entity
@Table(name="units_of_measure"
    ,catalog="extended"
)
public class UnitsOfMeasure  implements java.io.Serializable {


     private Integer unitId;
     private String unitName;
     private String unitDescription;
     private Set<DispensaryItems> dispensaryItemses = new HashSet<DispensaryItems>(0);
     private Set<PharmacyItem> pharmacyItems = new HashSet<PharmacyItem>(0);
     private Set<InventoryItems> inventoryItemses = new HashSet<InventoryItems>(0);
     private Set<LaboratoryItem> laboratoryItems = new HashSet<LaboratoryItem>(0);

    public UnitsOfMeasure() {
    }

	
    public UnitsOfMeasure(String unitName, String unitDescription) {
        this.unitName = unitName;
        this.unitDescription = unitDescription;
    }
    public UnitsOfMeasure(String unitName, String unitDescription, Set<DispensaryItems> dispensaryItemses, Set<PharmacyItem> pharmacyItems, Set<InventoryItems> inventoryItemses, Set<LaboratoryItem> laboratoryItems) {
       this.unitName = unitName;
       this.unitDescription = unitDescription;
       this.dispensaryItemses = dispensaryItemses;
       this.pharmacyItems = pharmacyItems;
       this.inventoryItemses = inventoryItemses;
       this.laboratoryItems = laboratoryItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="unit_id", unique=true, nullable=false)
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    
    @Column(name="unit_name", nullable=false, length=45)
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    
    @Column(name="unit_description", nullable=false, length=65535)
    public String getUnitDescription() {
        return this.unitDescription;
    }
    
    public void setUnitDescription(String unitDescription) {
        this.unitDescription = unitDescription;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unitsOfMeasure")
    public Set<DispensaryItems> getDispensaryItemses() {
        return this.dispensaryItemses;
    }
    
    public void setDispensaryItemses(Set<DispensaryItems> dispensaryItemses) {
        this.dispensaryItemses = dispensaryItemses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unitsOfMeasure")
    public Set<PharmacyItem> getPharmacyItems() {
        return this.pharmacyItems;
    }
    
    public void setPharmacyItems(Set<PharmacyItem> pharmacyItems) {
        this.pharmacyItems = pharmacyItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unitsOfMeasure")
    public Set<InventoryItems> getInventoryItemses() {
        return this.inventoryItemses;
    }
    
    public void setInventoryItemses(Set<InventoryItems> inventoryItemses) {
        this.inventoryItemses = inventoryItemses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unitsOfMeasure")
    public Set<LaboratoryItem> getLaboratoryItems() {
        return this.laboratoryItems;
    }
    
    public void setLaboratoryItems(Set<LaboratoryItem> laboratoryItems) {
        this.laboratoryItems = laboratoryItems;
    }




}


