package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Units generated by hbm2java
 */
@Entity
@Table(name="units"
    ,catalog="extended"
)
public class Units  implements java.io.Serializable {


     private Integer unitid;
     private String unitname;
     private String type;

    public Units() {
    }

    public Units(String unitname, String type) {
       this.unitname = unitname;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="unitid", unique=true, nullable=false)
    public Integer getUnitid() {
        return this.unitid;
    }
    
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }
    
    @Column(name="unitname", nullable=false, length=200)
    public String getUnitname() {
        return this.unitname;
    }
    
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }
    
    @Column(name="type", nullable=false, length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


