package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visitationtable generated by hbm2java
 */
@Entity
@Table(name="visitationtable"
    ,catalog="extended"
)
public class Visitationtable  implements java.io.Serializable {


     private Integer visitid;
     private String patientid;
     private Date date;
     private String vitals;
     private String doctor;
     private String status;
     private String patientstatus;
     private Date admissiondate;
     private Date dischargedate;
     private String previouslocstion;
     private int visittype;
     private String notes;
     private boolean review;
     private String month;
     private String year;
     private double totalBill;
     private double totalAmountPaid;
     private double depositedAmount;

    public Visitationtable() {
    }

	
    public Visitationtable(String patientid, int visittype, boolean review, String month, String year, double totalBill, double totalAmountPaid, double depositedAmount) {
        this.patientid = patientid;
        this.visittype = visittype;
        this.review = review;
        this.month = month;
        this.year = year;
        this.totalBill = totalBill;
        this.totalAmountPaid = totalAmountPaid;
        this.depositedAmount = depositedAmount;
    }
    public Visitationtable(String patientid, Date date, String vitals, String doctor, String status, String patientstatus, Date admissiondate, Date dischargedate, String previouslocstion, int visittype, String notes, boolean review, String month, String year, double totalBill, double totalAmountPaid, double depositedAmount) {
       this.patientid = patientid;
       this.date = date;
       this.vitals = vitals;
       this.doctor = doctor;
       this.status = status;
       this.patientstatus = patientstatus;
       this.admissiondate = admissiondate;
       this.dischargedate = dischargedate;
       this.previouslocstion = previouslocstion;
       this.visittype = visittype;
       this.notes = notes;
       this.review = review;
       this.month = month;
       this.year = year;
       this.totalBill = totalBill;
       this.totalAmountPaid = totalAmountPaid;
       this.depositedAmount = depositedAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="visitid", unique=true, nullable=false)
    public Integer getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(Integer visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="patientid", nullable=false, length=100)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="vitals", length=65535)
    public String getVitals() {
        return this.vitals;
    }
    
    public void setVitals(String vitals) {
        this.vitals = vitals;
    }
    
    @Column(name="doctor", length=100)
    public String getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(String doctor) {
        this.doctor = doctor;
    }
    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="patientstatus")
    public String getPatientstatus() {
        return this.patientstatus;
    }
    
    public void setPatientstatus(String patientstatus) {
        this.patientstatus = patientstatus;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="admissiondate", length=19)
    public Date getAdmissiondate() {
        return this.admissiondate;
    }
    
    public void setAdmissiondate(Date admissiondate) {
        this.admissiondate = admissiondate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dischargedate", length=10)
    public Date getDischargedate() {
        return this.dischargedate;
    }
    
    public void setDischargedate(Date dischargedate) {
        this.dischargedate = dischargedate;
    }
    
    @Column(name="previouslocstion")
    public String getPreviouslocstion() {
        return this.previouslocstion;
    }
    
    public void setPreviouslocstion(String previouslocstion) {
        this.previouslocstion = previouslocstion;
    }
    
    @Column(name="visittype", nullable=false)
    public int getVisittype() {
        return this.visittype;
    }
    
    public void setVisittype(int visittype) {
        this.visittype = visittype;
    }
    
    @Column(name="notes", length=65535)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="review", nullable=false)
    public boolean isReview() {
        return this.review;
    }
    
    public void setReview(boolean review) {
        this.review = review;
    }
    
    @Column(name="month", nullable=false, length=100)
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    
    @Column(name="year", nullable=false, length=100)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    
    @Column(name="total_bill", nullable=false, precision=22, scale=0)
    public double getTotalBill() {
        return this.totalBill;
    }
    
    public void setTotalBill(double totalBill) {
        this.totalBill = totalBill;
    }
    
    @Column(name="total_amount_paid", nullable=false, precision=22, scale=0)
    public double getTotalAmountPaid() {
        return this.totalAmountPaid;
    }
    
    public void setTotalAmountPaid(double totalAmountPaid) {
        this.totalAmountPaid = totalAmountPaid;
    }
    
    @Column(name="deposited_amount", nullable=false, precision=22, scale=0)
    public double getDepositedAmount() {
        return this.depositedAmount;
    }
    
    public void setDepositedAmount(double depositedAmount) {
        this.depositedAmount = depositedAmount;
    }




}


