package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VisitSymptoms generated by hbm2java
 */
@Entity
@Table(name="visit_symptoms"
    ,catalog="extended"
)
public class VisitSymptoms  implements java.io.Serializable {


     private Integer id;
     private int visitid;
     private String patientid;
     private int symptomid;
     private String note;

    public VisitSymptoms() {
    }

    public VisitSymptoms(int visitid, String patientid, int symptomid, String note) {
       this.visitid = visitid;
       this.patientid = patientid;
       this.symptomid = symptomid;
       this.note = note;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="visitid", nullable=false)
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    
    @Column(name="patientid", nullable=false, length=65535)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="symptomid", nullable=false)
    public int getSymptomid() {
        return this.symptomid;
    }
    
    public void setSymptomid(int symptomid) {
        this.symptomid = symptomid;
    }
    
    @Column(name="note", nullable=false, length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


