package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vitaltable generated by hbm2java
 */
@Entity
@Table(name="vitaltable"
    ,catalog="extended"
)
public class Vitaltable  implements java.io.Serializable {


     private int vitalid;
     private String patientid;
     private Double temperature;
     private Double height;
     private Double weight;
     private Double sistolic;
     private Double diatolic;
     private Double pulse;
     private String otherSymptons;
     private Date date;

    public Vitaltable() {
    }

	
    public Vitaltable(int vitalid, String patientid, Date date) {
        this.vitalid = vitalid;
        this.patientid = patientid;
        this.date = date;
    }
    public Vitaltable(int vitalid, String patientid, Double temperature, Double height, Double weight, Double sistolic, Double diatolic, Double pulse, String otherSymptons, Date date) {
       this.vitalid = vitalid;
       this.patientid = patientid;
       this.temperature = temperature;
       this.height = height;
       this.weight = weight;
       this.sistolic = sistolic;
       this.diatolic = diatolic;
       this.pulse = pulse;
       this.otherSymptons = otherSymptons;
       this.date = date;
    }
   
     @Id 
    
    @Column(name="vitalid", unique=true, nullable=false)
    public int getVitalid() {
        return this.vitalid;
    }
    
    public void setVitalid(int vitalid) {
        this.vitalid = vitalid;
    }
    
    @Column(name="patientid", nullable=false, length=100)
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    
    @Column(name="temperature", precision=22, scale=0)
    public Double getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }
    
    @Column(name="height", precision=22, scale=0)
    public Double getHeight() {
        return this.height;
    }
    
    public void setHeight(Double height) {
        this.height = height;
    }
    
    @Column(name="weight", precision=22, scale=0)
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    
    @Column(name="sistolic", precision=22, scale=0)
    public Double getSistolic() {
        return this.sistolic;
    }
    
    public void setSistolic(Double sistolic) {
        this.sistolic = sistolic;
    }
    
    @Column(name="diatolic", precision=22, scale=0)
    public Double getDiatolic() {
        return this.diatolic;
    }
    
    public void setDiatolic(Double diatolic) {
        this.diatolic = diatolic;
    }
    
    @Column(name="pulse", precision=22, scale=0)
    public Double getPulse() {
        return this.pulse;
    }
    
    public void setPulse(Double pulse) {
        this.pulse = pulse;
    }
    
    @Column(name="other_symptons", length=65535)
    public String getOtherSymptons() {
        return this.otherSymptons;
    }
    
    public void setOtherSymptons(String otherSymptons) {
        this.otherSymptons = otherSymptons;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


