package entities;
// Generated Nov 29, 2013 11:26:33 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ward generated by hbm2java
 */
@Entity
@Table(name="ward"
    ,catalog="extended"
)
public class Ward  implements java.io.Serializable {


     private Integer wardid;
     private String wardname;
     private int numberofbeds;
     private int occupied;
     private double cost;
     private String type;

    public Ward() {
    }

    public Ward(String wardname, int numberofbeds, int occupied, double cost, String type) {
       this.wardname = wardname;
       this.numberofbeds = numberofbeds;
       this.occupied = occupied;
       this.cost = cost;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="wardid", unique=true, nullable=false)
    public Integer getWardid() {
        return this.wardid;
    }
    
    public void setWardid(Integer wardid) {
        this.wardid = wardid;
    }
    
    @Column(name="wardname", nullable=false)
    public String getWardname() {
        return this.wardname;
    }
    
    public void setWardname(String wardname) {
        this.wardname = wardname;
    }
    
    @Column(name="numberofbeds", nullable=false)
    public int getNumberofbeds() {
        return this.numberofbeds;
    }
    
    public void setNumberofbeds(int numberofbeds) {
        this.numberofbeds = numberofbeds;
    }
    
    @Column(name="occupied", nullable=false)
    public int getOccupied() {
        return this.occupied;
    }
    
    public void setOccupied(int occupied) {
        this.occupied = occupied;
    }
    
    @Column(name="cost", nullable=false, precision=22, scale=0)
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }
    
    @Column(name="type", nullable=false, length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


